%% ACS ROAST/capMaker Example Walkthrough
% This is the public-facing walkthrough for the current ACS ROAST/capMaker
% workflow. It is designed to be run one cell at a time from the MATLAB
% editor. It keeps the main working path and removes most recovery/debug
% branches from the private development scratch workflow.
%
% High-level pipeline:
%   1. Import and segment a subject MRI.
%   2. Build a ROAST-derived full-head scalp mesh.
%   3. Register a phone scan to the MRI/capMaker frame.
%   4. Warp the shared scalp mesh toward the phone scan and crop it for
%      cap manufacturing.
%   5. Define headpost, ear/face, and chamber exclusion zones.
%   6. Build ROAST-compatible labels using the warped skin and titanium
%      headpost.
%   7. Generate an initial tES lead field, optimize a sparse montage, and
%      grow the candidate layout.
%   8. Add EEG positions and export capMaker manufacturing STLs.
%
% Large MRI, phone-scan, lead-field, and manufacturing products are not stored
% in git. See docs/example_data.md before trying to make a public dataset.
%
% ROAST credit: this workflow builds on ROAST. Please cite ROAST and the
% relevant targeting papers listed in CITATION.md when using this code.
%
% Safety note: this is research software, not a medical device. Inspect all
% intermediate geometry and simulation outputs before manufacturing or use.

%% 00 - Configure the tutorial run
% Run this cell first. For a fresh subject, edit the subject identifiers,
% path settings in acsUtilities/local.paths.json, and phone-scan filenames.
%
% The default settings favor reuse: if a product exists it is loaded; if it is
% missing, the relevant utility creates it or opens the needed picker GUI.
% Set force.* fields true only when you intentionally want to regenerate a
% product.

% clear;  % Uncomment only when intentionally starting a clean MATLAB session.
% clc;

repoRoot = pwd;
addpath(repoRoot);
addpath(fullfile(repoRoot, 'acsUtilities'));
addpath(fullfile(repoRoot, 'capMaker', 'geometry'));
addpath(fullfile(repoRoot, 'capMaker', 'core'));

cfg = struct();
cfg.subjectId = 'M2107';
cfg.subjectNickname = 'reeses';
cfg.segmentationTag = 'BONE_SHELL_ONLY';
cfg.t1Orientation = 'sar';
cfg.tpmOrientation = 'ras';

cfg.capDesignTag = 'rhdlpfc1';
cfg.phoneScanRunTag = 'lidarScan3_v02';
cfg.phoneScanScalpSource = 'roastScalp';
cfg.phoneScanGeometryTag = sprintf('%s_%s', ...
    cfg.phoneScanRunTag, cfg.phoneScanScalpSource);
cfg.phoneScanWarpTag = sprintf('%s_phoneWarp', cfg.phoneScanGeometryTag);
cfg.capDesignVariantTag = sprintf('%s_phoneWarp', cfg.capDesignTag);
cfg.leadFieldDesignTag = sprintf('%s_chamberTargetSmooth', ...
    cfg.capDesignVariantTag);

cfg.nInitialCandidates = 16;
cfg.nGrowthSteps = 3;
cfg.nNewCandidates = 8;
cfg.nTes = 8;
cfg.nEeg = 8;
cfg.tesTotalCurrentMa = 2;
cfg.tesMaxCurrentPerElectrodeMa = ...
    2 * cfg.tesTotalCurrentMa / cfg.nTes;

cfg.showFigures = true;
cfg.saveFigures = true;
cfg.useDummyLeadFields = false;
cfg.executeLeadFieldSolves = true;
cfg.saveLeadFieldRequestReports = true;
cfg.includeTitaniumInLeadFields = true;
cfg.runExactFinalLeadFieldAfterGrowth = true;
cfg.runTesChannelCountSweep = true;
cfg.runEegPrediction = true;
cfg.runChinStrapPreview = false;
cfg.runChinStrapDiagnostics = true;

cfg.electricFieldClimMode = 'brainPercentile';
cfg.electricFieldClimPercentile = 99.95;
electricFieldVisualizationOptions = { ...
    'electricFieldClimMode', cfg.electricFieldClimMode, ...
    'electricFieldClimPercentile', cfg.electricFieldClimPercentile};

cfg.growthAcquisitionMode = 'ucb';
cfg.growthUcbBeta = 1;
cfg.growthUcbUncertaintyMode = 'kernelVariance';
cfg.growthLeadFieldMode = 'surrogateExpanded';
cfg.tesChannelSweepCounts = 4:4:32;
cfg.tesChannelSweepEffectiveCurrentThresholdMa = 0.02;
cfg.tesChannelSweepEffectiveCurrentFraction = 0.05;
cfg.tesChannelSweepPlateauFractionOfBest = 0.95;

cfg.placementNormalMode = 'smooth';
cfg.placementNormalUpDotMin = 0.25;
cfg.placementNormalSmoothRadiusMm = 6;
cfg.holderNormalMode = 'autoSmooth';
cfg.holderSmoothNormalRadiusMm = 6;
cfg.holderNormalDeviationThresholdDeg = 25;
cfg.holderMaxRawToSmoothNormalAngleDeg = 25;

cfg.strapExclusionMode = 'auto';
cfg.strapRostralOffsetMm = 0;
cfg.strapWidthMm = 10;
cfg.strapMarginMm = 2;
cfg.strapExclusionRadiusMm = [];
cfg.strapLateralLengthMm = 35;
cfg.strapSampleSpacingMm = 5;

cfg.phoneScanPrinterBedSkinMaxFaces = 1200;
cfg.phoneScanWarpInfluenceRadiusMm = 90;
cfg.phoneScanWarpInfluenceSigmaMm = 45;
cfg.phoneScanWarpSmoothingIterations = 80;
cfg.phoneScanWarpSmoothingBlend = 0.55;
cfg.phoneScanWarpSurfaceSmoothingIterations = 8;
cfg.phoneScanWarpSurfaceSmoothingLambda = 0.35;
cfg.phoneScanWarpSurfaceSmoothingMu = -0.37;
cfg.phoneScanWarpSeedWeight = 0.45;
cfg.phoneScanWarpDisplacementScale = 1.0;
cfg.phoneScanWarpMaxInflationMm = 45;
cfg.phoneScanWarpRobustUpperPercentile = 99.9;

cfg.phoneScanWarpDentRepairMode = 'auto';
cfg.phoneScanWarpDentRepairMetric = 'localLaplacian';
cfg.phoneScanWarpDentRepairIterations = 5;
cfg.phoneScanWarpDentRepairRadiusMm = 8;
cfg.phoneScanWarpDentRepairEnvelopePercentile = 75;
cfg.phoneScanWarpDentRepairMinDentMm = 1.0;
cfg.phoneScanWarpDentRepairNormalAngleDeg = 35;
cfg.phoneScanWarpDentRepairLocalSmoothingIterations = 3;
cfg.phoneScanWarpDentRepairDirectionRadialWeight = 0.25;
cfg.phoneScanWarpDentRepairBlend = 0.85;
cfg.phoneScanWarpDentRepairMaxMoveMm = 12;
cfg.phoneScanWarpDentRepairMaxRings = 8;
cfg.phoneScanWarpDentRepairMaxFlaggedFraction = 0.08;

cfg.manualFullDentRepairEditMode = 'never';
cfg.manualCroppedDentRepairEditMode = 'auto';
cfg.manualDentRepairBrushRadiusMm = 4;
cfg.manualDentRepairSelectionDepthMm = 3;

cfg.phoneScanCropEditMode = 'auto';
cfg.phoneScanFiducialEditMode = 'auto';
cfg.phoneScanHeadpostObjectEditMode = 'auto';
cfg.phoneScanCropPlaneMode = 'autoSelect';
cfg.earEditMode = 'auto';
cfg.modelFiducialEditMode = 'auto';

force = struct();
force.segmentation = false;
force.phoneScanBaseSkinCache = false;
force.phoneScanCrop = false;
force.phoneScanFiducials = false;
force.phoneScanRegistration = false;
force.phoneScanHeadpostObject = false;
force.phoneScanWarp = false;
force.phoneScanPrinterBedCrop = false;
force.manualFullDentRepair = false;
force.manualCroppedDentRepair = false;
force.phoneScanHeadpostExclusion = false;
force.phoneScanEarExclusions = false;
force.headpostPlacement = false;
force.headpostPlacementExclusion = false;
force.stereotaxicLandmarks = false;
force.targetPick = false;
force.chamberPlan = false;
force.activeRoastMaskCleanup = false;
force.surfaceBundleRoastLabels = false;
force.layoutProducts = false;
force.manufacturing = false;

P = struct();
P.capWorkFolder = acsSubjectPath(cfg.subjectId, 'capWork');
P.segmentationFolder = fullfile(repoRoot, 'outputs', 'subjects', ...
    cfg.subjectId, 'segmentation', cfg.segmentationTag);
P.segmentationReportFile = fullfile(P.segmentationFolder, ...
    sprintf('%s_T1_RAS_fromSAR_spmSegmentationReport.mat', cfg.subjectId));

P.phoneScanRawPlyFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_lidarScan3_30jul2026.ply', cfg.subjectId));
P.phoneScanCropTag = sprintf('%s_lidarScan3_30jul2026_headCrop_v02', ...
    cfg.subjectId);
P.phoneScanCropFile = fullfile(P.capWorkFolder, ...
    [P.phoneScanCropTag '.mat']);
P.phoneScanCroppedPlyFile = fullfile(P.capWorkFolder, ...
    [P.phoneScanCropTag '.ply']);
P.phoneScanFiducialsFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_phoneScanFiducials.mat', P.phoneScanCropTag));
P.phoneScanBaseSkinCacheFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_baseFullHeadSkinMesh.mat', ...
    cfg.subjectId, cfg.phoneScanGeometryTag));
P.phoneScanRegistrationFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_phoneToMriFullHeadRegistration.mat', ...
    cfg.subjectId, cfg.phoneScanGeometryTag));
P.phoneScanHeadpostObjectFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_phoneHeadpostObject.mat', ...
    cfg.subjectId, cfg.phoneScanGeometryTag));
P.phoneScanWarpCacheFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_warpedFullHeadSkinMesh.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanManualDentRepairCacheFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_warpedFullHeadSkinMesh_manualDentRepair.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanPrinterBedSkinCacheFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_printerBedSkinMesh.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanCroppedManualDentRepairCacheFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_printerBedSkinMesh_manualDentRepair.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanBedCropPlaneFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_printerBedCropPlane.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanHeadpostExclusionFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_headpostKeepout.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.phoneScanEarExclusionFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_printerBedEarExclusions.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.headpostPlacementFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_headpostPlacement_v01.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.headpostPlacementExclusionFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_headpostPlacementKeepout_v01.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
P.stereotaxicLandmarkFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_stereotaxicLandmarks_T1.mat', cfg.subjectId));
P.chamberTargetFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_recordingChamberTarget_%s.mat', ...
    cfg.subjectId, cfg.capDesignTag));
P.chamberPlanFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_recordingChamberPlan_%s.mat', ...
    cfg.subjectId, cfg.capDesignTag));
P.surfaceBundleFile = fullfile(P.capWorkFolder, ...
    sprintf('%s_%s_roastSurfaceBundle_withImplants.mat', ...
    cfg.subjectId, cfg.phoneScanWarpTag));

manufacturingTag = sprintf('%s_tes%d_eeg%d_%s', ...
    cfg.subjectId, cfg.nTes, cfg.nEeg, cfg.capDesignVariantTag);

anatomicalFiducialLabels = {'Nas', 'Lpa', 'Rpa', 'Sep', 'Loc', 'Roc', 'Ini'};

%% 00.5 - Inspect generated-data locations before a fresh start
% This cell is intentionally non-destructive. Delete generated products only
% after confirming raw/manual inputs are preserved.

cacheMap = struct();
cacheMap.generatedFolders = { ...
    fullfile(repoRoot, 'outputs', 'subjects', cfg.subjectId, 'anatomy'); ...
    P.segmentationFolder; ...
    fullfile(P.capWorkFolder, 'qc'); ...
    fullfile(P.capWorkFolder, 'manufacturing')};
cacheMap.rawOrManualInputs = { ...
    P.phoneScanRawPlyFile; ...
    P.phoneScanCropFile; ...
    P.phoneScanFiducialsFile; ...
    P.phoneScanHeadpostObjectFile; ...
    P.phoneScanEarExclusionFile; ...
    P.stereotaxicLandmarkFile; ...
    P.chamberTargetFile};

disp('Generated folders:');
disp(cacheMap.generatedFolders);
disp('Raw/manual products worth preserving:');
disp(cacheMap.rawOrManualInputs);

%% 01 - Import the DICOM anatomy and run segmentation
% Interactive: no.
% Slow: segmentation can be slow.
% Output: canonical T1 NIfTI, SPM tissue maps, and ROAST hard-label mask.

importOut = acsImportDicomAnatomy(cfg.subjectId, ...
    'verbose', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'qcTitleMode', 'compact');

if exist(P.segmentationReportFile, 'file') == 2 && ~force.segmentation
    S = load(P.segmentationReportFile);
    segOut = S.out;
    fprintf('Reusing segmentation report: %s\n', P.segmentationReportFile);
else
    segOut = acsSegmentAnatomyWithTpm(cfg.subjectId, ...
        'segmentationTag', cfg.segmentationTag, ...
        't1Orientation', cfg.t1Orientation, ...
        'tpmOrientation', cfg.tpmOrientation, ...
        'boneMode', 'shellOnly', ...
        'forceRoastLabels', false, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
end

%% 02 - Build a ROAST-derived full-head scalp cache and model fiducials
% Interactive: model fiducials may open a picker on first run.
% Output: full-head scalp mesh in the capMaker pre-crop frame, plus reusable
% model-space landmarks for phone-scan and Polhemus registration.

phoneScanBaseSkinCache = acsBuildRoastScalpSkinCache(segOut, ...
    'outputFile', P.phoneScanBaseSkinCacheFile, ...
    'force', force.phoneScanBaseSkinCache, ...
    'maxFaces', 35000, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

modelFiducials = acsSelectModelFiducials(segOut, ...
    'fiducialLabels', anatomicalFiducialLabels, ...
    'meshStage', 'fullHead', ...
    'editMode', cfg.modelFiducialEditMode, ...
    'skinCacheFile', phoneScanBaseSkinCache.cacheFile, ...
    'forceSkinMesh', false, ...
    'skinMeshOptions', struct(), ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 03 - Register the phone scan to the MRI/capMaker frame
% Interactive: phone-scan crop, fiducials, and headpost-object painting may
% open GUIs on first run.
% Output: registered phone-scan surface and a painted set of visible
% headpost points.

reusePhoneCrop = exist(P.phoneScanCropFile, 'file') == 2 && ...
    ~force.phoneScanCrop && ~strcmpi(cfg.phoneScanCropEditMode, 'always');
if reusePhoneCrop
    S = load(P.phoneScanCropFile);
    if isfield(S, 'outForSave')
        phoneCrop = S.outForSave;
    elseif isfield(S, 'out')
        phoneCrop = S.out;
    else
        phoneCrop = S;
    end
    fprintf('Reusing phone scan crop: %s\n', P.phoneScanCropFile);
else
    phoneCrop = acsCropPhoneScanToHead(P.phoneScanRawPlyFile, ...
        'outputTag', P.phoneScanCropTag, ...
        'outputFile', P.phoneScanCropFile, ...
        'outputPlyFile', P.phoneScanCroppedPlyFile, ...
        'interactive', true, ...
        'keepLargestComponent', true, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'force', true, ...
        'verbose', true);
end

phoneFids = acsSelectPhoneScanFiducials(P.phoneScanCropFile, ...
    'fiducialLabels', anatomicalFiducialLabels, ...
    'outputFile', P.phoneScanFiducialsFile, ...
    'editMode', cfg.phoneScanFiducialEditMode, ...
    'force', force.phoneScanFiducials, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

phoneReg = acsRegisterPhoneScanToCapMakerFrame(P.phoneScanCropFile, [], ...
    'phoneFiducialsFile', phoneFids.outputFile, ...
    'modelFiducialsFile', modelFiducials.outputFile, ...
    'fiducialLabels', 'auto', ...
    'targetFrame', 'modelFiducials', ...
    'initializationMode', 'fiducial', ...
    'transformType', 'rigid', ...
    'icpIterations', 0, ...
    'outputFile', P.phoneScanRegistrationFile, ...
    'force', force.phoneScanRegistration, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

phoneObjectSourceSkinFile = '';
if isfield(phoneReg, 'target') && isstruct(phoneReg.target) && ...
        isfield(phoneReg.target, 'file') && ~isempty(phoneReg.target.file)
    phoneObjectSourceSkinFile = phoneReg.target.file;
end

phoneHeadpostObject = acsSelectPhoneScanObject(phoneReg, ...
    'objectName', 'headpost', ...
    'outputFile', P.phoneScanHeadpostObjectFile, ...
    'editMode', cfg.phoneScanHeadpostObjectEditMode, ...
    'force', force.phoneScanHeadpostObject, ...
    'brushRadiusMm', 8, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 04 - Warp the scalp to the phone scan and crop to the printer bed
% Interactive: crop-plane GUI may open if no saved crop exists or edit mode
% requests it. Manual dent repair can open if enabled in section 00.
% Output: active capMaker skin cache in print-frame millimeters.

clear acsWarpScalpSurfaceToPhoneScan acsWarpScalpSurfaceToPolhemusTrace
scalpWarp = acsWarpScalpSurfaceToPhoneScan(phoneScanBaseSkinCache.cacheFile, ...
    phoneReg, ...
    'outputFile', P.phoneScanWarpCacheFile, ...
    'outputTag', cfg.phoneScanWarpTag, ...
    'force', force.phoneScanWarp, ...
    'phoneObjectExclusionFile', phoneHeadpostObject.outputFile, ...
    'excludePhoneObjectPoints', true, ...
    'phoneObjectExclusionDistanceMm', 4, ...
    'excludeHeadpostPoints', false, ...
    'maxTraceDistanceMm', 75, ...
    'maxInflationMm', cfg.phoneScanWarpMaxInflationMm, ...
    'displacementScale', cfg.phoneScanWarpDisplacementScale, ...
    'robustUpperPercentile', cfg.phoneScanWarpRobustUpperPercentile, ...
    'influenceRadiusMm', cfg.phoneScanWarpInfluenceRadiusMm, ...
    'influenceSigmaMm', cfg.phoneScanWarpInfluenceSigmaMm, ...
    'coverageOffsetToleranceMm', 0.5, ...
    'smoothingIterations', cfg.phoneScanWarpSmoothingIterations, ...
    'smoothingBlend', cfg.phoneScanWarpSmoothingBlend, ...
    'surfaceSmoothingIterations', cfg.phoneScanWarpSurfaceSmoothingIterations, ...
    'surfaceSmoothingLambda', cfg.phoneScanWarpSurfaceSmoothingLambda, ...
    'surfaceSmoothingMu', cfg.phoneScanWarpSurfaceSmoothingMu, ...
    'surfaceSmoothingPreserveBoundary', true, ...
    'dentRepairMode', cfg.phoneScanWarpDentRepairMode, ...
    'dentRepairMetric', cfg.phoneScanWarpDentRepairMetric, ...
    'dentRepairIterations', cfg.phoneScanWarpDentRepairIterations, ...
    'dentRepairRadiusMm', cfg.phoneScanWarpDentRepairRadiusMm, ...
    'dentRepairEnvelopePercentile', ...
        cfg.phoneScanWarpDentRepairEnvelopePercentile, ...
    'dentRepairMinDentMm', cfg.phoneScanWarpDentRepairMinDentMm, ...
    'dentRepairNormalAngleDeg', cfg.phoneScanWarpDentRepairNormalAngleDeg, ...
    'dentRepairLocalSmoothingIterations', ...
        cfg.phoneScanWarpDentRepairLocalSmoothingIterations, ...
    'dentRepairDirectionRadialWeight', ...
        cfg.phoneScanWarpDentRepairDirectionRadialWeight, ...
    'dentRepairBlend', cfg.phoneScanWarpDentRepairBlend, ...
    'dentRepairMaxMoveMm', cfg.phoneScanWarpDentRepairMaxMoveMm, ...
    'dentRepairMaxRings', cfg.phoneScanWarpDentRepairMaxRings, ...
    'dentRepairMaxFlaggedFraction', ...
        cfg.phoneScanWarpDentRepairMaxFlaggedFraction, ...
    'dentRepairProtectBoundary', true, ...
    'seedWeight', cfg.phoneScanWarpSeedWeight, ...
    'normalOrientationMode', 'autoRadial', ...
    'warpDirectionMode', 'blendRadial', ...
    'warpRadialBlendThreshold', 0.35, ...
    'offsetProjectionMode', 'maxWarpRadial', ...
    'makeRoastMask', false, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

activeWarpedFullHeadSkinCacheFile = scalpWarp.outputFile;
if isfield(scalpWarp, 'cacheFile') && ~isempty(scalpWarp.cacheFile)
    activeWarpedFullHeadSkinCacheFile = scalpWarp.cacheFile;
end

if ~strcmpi(cfg.manualFullDentRepairEditMode, 'never')
    manualDentRepair = acsInteractivelyRepairSkinDents( ...
        activeWarpedFullHeadSkinCacheFile, ...
        'meshStage', 'stableHead', ...
        'outputFile', P.phoneScanManualDentRepairCacheFile, ...
        'editMode', cfg.manualFullDentRepairEditMode, ...
        'force', force.manualFullDentRepair, ...
        'brushRadiusMm', cfg.manualDentRepairBrushRadiusMm, ...
        'selectOnlyDentFlags', true, ...
        'selectionDepthMm', cfg.manualDentRepairSelectionDepthMm, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
    if isfield(manualDentRepair, 'outputFile') && ...
            exist(manualDentRepair.outputFile, 'file') == 2
        activeWarpedFullHeadSkinCacheFile = manualDentRepair.outputFile;
    end
end

phoneBedSkin = acsCropWarpedSkinCacheToPrinterBed( ...
    activeWarpedFullHeadSkinCacheFile, ...
    'outputFile', P.phoneScanPrinterBedSkinCacheFile, ...
    'outputTag', 'printerBedSkinMesh', ...
    'cropPlaneFile', P.phoneScanBedCropPlaneFile, ...
    'cropPlaneMode', cfg.phoneScanCropPlaneMode, ...
    'cropSide', 'top', ...
    'alignCrop', true, ...
    'dropToZ0', true, ...
    'centerXY', true, ...
    'contextObjectFile', phoneHeadpostObject.outputFile, ...
    'contextSourceSkinCacheFile', phoneObjectSourceSkinFile, ...
    'skinMaxFaces', cfg.phoneScanPrinterBedSkinMaxFaces, ...
    'keepLargestSkinComponent', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'force', force.phoneScanPrinterBedCrop, ...
    'verbose', true);

skinCacheForCap = phoneBedSkin.cacheFile;
if ~strcmpi(cfg.manualCroppedDentRepairEditMode, 'never')
    croppedDentRepair = acsInteractivelyRepairSkinDents(skinCacheForCap, ...
        'meshStage', 'skin', ...
        'outputFile', P.phoneScanCroppedManualDentRepairCacheFile, ...
        'editMode', cfg.manualCroppedDentRepairEditMode, ...
        'force', force.manualCroppedDentRepair, ...
        'brushRadiusMm', cfg.manualDentRepairBrushRadiusMm, ...
        'selectOnlyDentFlags', true, ...
        'selectionDepthMm', cfg.manualDentRepairSelectionDepthMm, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
    if isfield(croppedDentRepair, 'outputFile') && ...
            exist(croppedDentRepair.outputFile, 'file') == 2
        skinCacheForCap = croppedDentRepair.outputFile;
    end
end
skinCacheForManufacturing = skinCacheForCap;

Sskin = load(skinCacheForCap, 'TRskin');
Vskin = double(Sskin.TRskin.Points);
fprintf('\nActive capMaker skin cache\n');
fprintf('  file: %s\n', skinCacheForCap);
fprintf('  vertices/faces: %d / %d\n', ...
    size(Vskin, 1), size(Sskin.TRskin.ConnectivityList, 1));
fprintf('  bounds mm: X[%.1f %.1f], Y[%.1f %.1f], Z[%.1f %.1f]\n\n', ...
    min(Vskin(:, 1)), max(Vskin(:, 1)), ...
    min(Vskin(:, 2)), max(Vskin(:, 2)), ...
    min(Vskin(:, 3)), max(Vskin(:, 3)));

%% 04.5 - Inspect the warped/cropped skin mesh and label-mask context
% Interactive: optional slice paging in the label QC figure.
% Output: QC figures only. This does not change the active mesh.

skinMeshInspectionFullHead = acsInspectCapMakerSkinMesh( ...
    activeWarpedFullHeadSkinCacheFile, ...
    'meshStage', 'stableHead', ...
    'colorMode', 'dent', ...
    'dentMetric', cfg.phoneScanWarpDentRepairMetric, ...
    'dentRadiusMm', cfg.phoneScanWarpDentRepairRadiusMm, ...
    'dentEnvelopePercentile', cfg.phoneScanWarpDentRepairEnvelopePercentile, ...
    'dentMinDepthMm', cfg.phoneScanWarpDentRepairMinDentMm, ...
    'dentNormalAngleDeg', cfg.phoneScanWarpDentRepairNormalAngleDeg, ...
    'normalSmoothIterations', 4, ...
    'showNormals', false, ...
    'showFigures', cfg.showFigures, ...
    'verbose', true);

skinMeshInspectionCropped = acsInspectCapMakerSkinMesh(skinCacheForCap, ...
    'meshStage', 'skin', ...
    'colorMode', 'dent', ...
    'dentMetric', cfg.phoneScanWarpDentRepairMetric, ...
    'dentRadiusMm', cfg.phoneScanWarpDentRepairRadiusMm, ...
    'dentEnvelopePercentile', cfg.phoneScanWarpDentRepairEnvelopePercentile, ...
    'dentMinDepthMm', cfg.phoneScanWarpDentRepairMinDentMm, ...
    'dentNormalAngleDeg', cfg.phoneScanWarpDentRepairNormalAngleDeg, ...
    'normalSmoothIterations', 4, ...
    'showNormals', false, ...
    'showFigures', cfg.showFigures, ...
    'verbose', true);

[maskFolderForCap, maskStemForCap, maskExtForCap] = ...
    fileparts(segOut.roastReady.maskFile);
if isempty(maskExtForCap)
    maskExtForCap = '.nii';
end
activeRoastSkinCleanMaskFile = fullfile(maskFolderForCap, ...
    sprintf('%s_%s_skinClean%s', ...
    maskStemForCap, cfg.phoneScanWarpTag, maskExtForCap));

activeRoastLayoutMaskFile = segOut.roastReady.maskFile;

activeRoastMaskQc = acsCleanAndVisualizeRoastLabelMask( ...
    activeRoastLayoutMaskFile, ...
    't1File', segOut.roastReady.t1File, ...
    'outputFile', activeRoastSkinCleanMaskFile, ...
    'force', force.activeRoastMaskCleanup, ...
    'cleanupSkinComponents', true, ...
    'skinCleanupMode', 'largest', ...
    'surfaceOverlayFile', activeWarpedFullHeadSkinCacheFile, ...
    'surfaceOverlayStage', 'stableHead', ...
    'surfaceOverlayColor', [1 1 1], ...
    'enableSlicePaging', cfg.showFigures, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);
activeRoastLayoutMaskFile = activeRoastMaskQc.maskFile;

%% 05 - Define headpost, ear/face, and chamber exclusions
% Interactive: ear/face exclusion and chamber target/placement can open GUIs.
% Output: placement keepouts in capMaker print-frame coordinates.

phoneHeadpostExclusion = acsMakeImplantExclusionFromPhoneObject( ...
    phoneHeadpostObject.outputFile, skinCacheForCap, ...
    'sourceSkinCacheFile', phoneObjectSourceSkinFile, ...
    'objectName', 'headpost', ...
    'marginMm', 5, ...
    'outputFile', P.phoneScanHeadpostExclusionFile, ...
    'projectionMode', 'auto', ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'force', force.phoneScanHeadpostExclusion, ...
    'verbose', true);

activeEarExclusions = acsSelectEarExclusionSpheres(skinCacheForCap, ...
    'outputFile', P.phoneScanEarExclusionFile, ...
    'editMode', cfg.earEditMode, ...
    'force', force.phoneScanEarExclusions, ...
    'showFigures', ~strcmpi(cfg.earEditMode, 'never'), ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);
activeEarExclusionFile = activeEarExclusions.outputFile;

headpostPlacement = acsPlanHeadpostPlacement( ...
    phoneHeadpostExclusion, skinCacheForCap, ...
    'maskFile', activeRoastLayoutMaskFile, ...
    'outputFile', P.headpostPlacementFile, ...
    'alignPostToSkullNormal', true, ...
    'normalSearchRadiusMm', 8, ...
    'bendThicknessMode', 'postNormal', ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'force', force.headpostPlacement);

headpostPlacementExclusion = acsMakeHeadpostExclusionFromPlacement( ...
    headpostPlacement, skinCacheForCap, ...
    'objectName', 'headpost', ...
    'marginMm', 5, ...
    'footprintMode', 'postCylinder', ...
    'outputFile', P.headpostPlacementExclusionFile, ...
    'force', force.headpostPlacementExclusion, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);
headpostExclusionFile = headpostPlacementExclusion.outputFile;

stereoLandmarks = acsSelectStereotaxicLandmarks( ...
    segOut.roastReady.t1File, ...
    'landmarkLabels', {'LeftEarBar', 'RightEarBar', ...
    'LeftOrbit', 'RightOrbit'}, ...
    'outputFile', P.stereotaxicLandmarkFile, ...
    'force', force.stereotaxicLandmarks, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

chamberPlan = acsPlanChamberPlacement(segOut, ...
    'targetVoxel', [], ...
    'targetVoxelFile', P.chamberTargetFile, ...
    'forceTargetPick', force.targetPick, ...
    'maskFile', activeRoastLayoutMaskFile, ...
    'skinCacheFile', skinCacheForCap, ...
    'contextExclusionFile', headpostExclusionFile, ...
    'stereotaxicLandmarks', stereoLandmarks, ...
    'chamberOuterDiameterMm', 25, ...
    'chamberInnerDiameterMm', 19, ...
    'chamberHeightMm', 19, ...
    'exclusionMarginMm', 5, ...
    'outerSkullOnly', true, ...
    'checkChamberSkullIntersection', true, ...
    'displaySkullSurfaceMaxFaces', 15000, ...
    'interactive', true, ...
    'reviewExisting', true, ...
    'outputFile', P.chamberPlanFile, ...
    'force', force.chamberPlan, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);
chamberExclusionFile = chamberPlan.outputFile;

tesTargetVoxel = double(chamberPlan.targetVoxel);
tesTargetOrientation = repmat([0 0 1], size(tesTargetVoxel, 1), 1);
if isfield(chamberPlan, 'placement') && ...
        isfield(chamberPlan.placement, 'trackDirectionInWorld')
    candidateOrientation = double(chamberPlan.placement.trackDirectionInWorld(:)');
    if numel(candidateOrientation) == 3 && all(isfinite(candidateOrientation)) && ...
            norm(candidateOrientation) > eps
        candidateOrientation = candidateOrientation ./ norm(candidateOrientation);
        tesTargetOrientation = repmat(candidateOrientation, ...
            size(tesTargetVoxel, 1), 1);
    end
end

%% 06 - Build ROAST labels and cap placement exclusions
% Slow: surface-derived label writing can be slow.
% Output: active ROAST layout mask, optional titanium solve mask, and cap
% placement exclusion centers/radii.

surfaceBundleRoastLabelsFile = fullfile(P.segmentationFolder, ...
    sprintf('%s_%s_surfaceBundleSkin_T1orT2_SPM_masks.nii', ...
    cfg.subjectId, cfg.phoneScanWarpTag));
surfaceBundleRoastLabelsTitaniumFile = fullfile(P.segmentationFolder, ...
    sprintf('%s_%s_surfaceBundleSkinHeadpostTi_T1orT2_SPM_masks.nii', ...
    cfg.subjectId, cfg.phoneScanWarpTag));

meshNativeRoastBundle = acsBuildRoastSurfaceBundle(segOut, ...
    'referenceScalpSkinCacheFile', phoneScanBaseSkinCache.cacheFile, ...
    'referenceScalpMeshStage', 'stableHead', ...
    'scalpSkinCacheFile', activeWarpedFullHeadSkinCacheFile, ...
    'scalpMeshStage', 'stableHead', ...
    'headpostPlacementFile', headpostPlacement.outputFile, ...
    'headpostSkinCacheFile', skinCacheForCap, ...
    'outputFile', P.surfaceBundleFile, ...
    'force', false, ...
    'maxFacesPerTissue', Inf, ...
    'skinShellMaxFaces', Inf, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

surfaceBundleRoastLabelsSkinOnly = acsMakeRoastLabelsFromSurfaceBundle( ...
    meshNativeRoastBundle, ...
    'baseMaskFile', segOut.roastReady.maskFile, ...
    't1File', segOut.roastReady.t1File, ...
    'outputFile', surfaceBundleRoastLabelsFile, ...
    'force', force.surfaceBundleRoastLabels, ...
    'applySkin', true, ...
    'applyTitanium', false, ...
    'voxelizationAxes', [1 2 3], ...
    'voxelizationVoteRule', 'majority', ...
    'gridChunkSizeZ', 12, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

activeRoastLayoutMaskFile = surfaceBundleRoastLabelsSkinOnly.maskFile;
activeRoastSolveMaskFile = activeRoastLayoutMaskFile;
activeRoastExtraTissues = [];
activeRoastConductivities = struct();

if cfg.includeTitaniumInLeadFields
    surfaceBundleRoastLabelsWithTitanium = ...
        acsMakeRoastLabelsFromSurfaceBundle( ...
        meshNativeRoastBundle, ...
        'baseMaskFile', surfaceBundleRoastLabelsSkinOnly.maskFile, ...
        't1File', segOut.roastReady.t1File, ...
        'outputFile', surfaceBundleRoastLabelsTitaniumFile, ...
        'force', force.surfaceBundleRoastLabels, ...
        'applySkin', false, ...
        'applyTitanium', true, ...
        'voxelizationAxes', [1 2 3], ...
        'voxelizationVoteRule', 'majority', ...
        'gridChunkSizeZ', 12, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);

    if isfield(surfaceBundleRoastLabelsWithTitanium, 'extraTissues') && ...
            ~isempty(surfaceBundleRoastLabelsWithTitanium.extraTissues)
        activeRoastSolveMaskFile = surfaceBundleRoastLabelsWithTitanium.maskFile;
        activeRoastExtraTissues = ...
            surfaceBundleRoastLabelsWithTitanium.extraTissues;
        activeRoastConductivities = ...
            surfaceBundleRoastLabelsWithTitanium.conductivities;
        cfg.leadFieldDesignTag = sprintf('%s_headpostTi', ...
            cfg.leadFieldDesignTag);
    end
end

implantExclusionFiles = {headpostExclusionFile; chamberExclusionFile};
[placementExclusionCenters, placementExclusionRadii, ...
    placementExclusionInfo] = acsPlacementExclusionsFromImplantFiles( ...
    implantExclusionFiles, ...
    'extraMarginMm', 0, ...
    'verbose', true);

targetOptsBase = struct( ...
    'placementMode', 'surfaceGeodesic', ...
    'edgeMarginMM', 10, ...
    'midlineMarginMM', 10, ...
    'preferSymmetry', true, ...
    'normalUpDotMin', cfg.placementNormalUpDotMin, ...
    'normalMode', cfg.placementNormalMode, ...
    'normalSmoothRadiusMM', cfg.placementNormalSmoothRadiusMm, ...
    'visibleFromAbove', true, ...
    'visibilityBinMM', 2, ...
    'visibilityDepthMM', 2, ...
    'vizSurfaceGeodesic', cfg.showFigures);
if ~isempty(placementExclusionCenters)
    targetOptsBase.exclusionCenters = placementExclusionCenters;
    targetOptsBase.exclusionRadiusMM = placementExclusionRadii;
end

%% 07 - Build the initial candidate layout and lead field
% Slow: ROAST lead-field generation is expensive when executeLeadFieldSolves
% is true.
% Output: layout16 and lf16.

layout16 = acsMakeRoastCapMakerLayout(segOut, ...
    'nElectrodes', cfg.nInitialCandidates, ...
    'maskFile', activeRoastLayoutMaskFile, ...
    'surfaceSource', 'capMaker', ...
    'skinCacheFile', skinCacheForCap, ...
    'targetOptions', targetOptsBase, ...
    'cropPlaneMode', 'default', ...
    'earExclusionMode', cfg.earEditMode, ...
    'earExclusionFile', activeEarExclusionFile, ...
    'strapExclusionMode', cfg.strapExclusionMode, ...
    'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
    'strapWidthMm', cfg.strapWidthMm, ...
    'strapMarginMm', cfg.strapMarginMm, ...
    'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
    'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
    'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
    'forceLayout', force.layoutProducts, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

mainLeadFieldTag = sprintf('%s_capMakerGeo_lf%d_%s', ...
    cfg.subjectId, cfg.nInitialCandidates, cfg.leadFieldDesignTag);
if cfg.includeTitaniumInLeadFields && ~isempty(activeRoastExtraTissues)
    mainLeadFieldTag = sprintf('%s_withTi', mainLeadFieldTag);
else
    mainLeadFieldTag = sprintf('%s_noTi', mainLeadFieldTag);
end

mainSegMaskFile = activeRoastSolveMaskFile;
mainExtraTissues = activeRoastExtraTissues;
mainConductivities = activeRoastConductivities;
mainRoastExtraOptions = {'segMaskFile', mainSegMaskFile};
if ~isempty(mainExtraTissues)
    mainRoastExtraOptions = [mainRoastExtraOptions, { ...
        'extraTissues', mainExtraTissues, ...
        'conductivities', mainConductivities}];
end
mainRoastExtraOptions = [mainRoastExtraOptions, ...
    electricFieldVisualizationOptions];

if cfg.useDummyLeadFields
    lf16 = acsGenerateDummyRoastLeadField(layout16, ...
        'simulationTag', sprintf('DUMMY_%s', mainLeadFieldTag), ...
        'force', true);
else
    lf16 = acsGenerateRoastLeadField(layout16, ...
        'simulationTag', mainLeadFieldTag, ...
        'electrodeModel', 'biosemiPin', ...
        'segMaskFile', mainSegMaskFile, ...
        'extraTissues', mainExtraTissues, ...
        'conductivities', mainConductivities, ...
        'resampling', 'off', ...
        'roastOptions', electricFieldVisualizationOptions, ...
        'execute', cfg.executeLeadFieldSolves, ...
        'saveReport', cfg.saveLeadFieldRequestReports);
end

%% 08 - Optimize the initial sparse tES montage
% Output: sparse16 and a QC field plot. Invalid manufacturing sites are
% excluded from selection but can still be useful for surrogate prediction.

leadFieldSearchMode = 'globalCvx';
if cfg.useDummyLeadFields
    leadFieldSearchMode = 'developmentHeuristic';
end

siteValidity16 = acsEvaluateCapMakerManufacturingSites(layout16, ...
    'strapExclusionMode', cfg.strapExclusionMode, ...
    'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
    'strapWidthMm', cfg.strapWidthMm, ...
    'strapMarginMm', cfg.strapMarginMm, ...
    'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
    'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
    'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
    'holderNormalMode', cfg.holderNormalMode, ...
    'holderSmoothNormalRadiusMm', cfg.holderSmoothNormalRadiusMm, ...
    'holderNormalDeviationThresholdDeg', ...
        cfg.holderNormalDeviationThresholdDeg, ...
    'holderMinAxisZ', cfg.placementNormalUpDotMin, ...
    'holderMaxRawToSmoothNormalAngleDeg', ...
        cfg.holderMaxRawToSmoothNormalAngleDeg, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

sparseExcludedNames16 = siteValidity16.invalidNames(:);
sparse16 = acsOptimizeSparseRoastLeadField(layout16.t1File, ...
    lf16.simulationTag, ...
    tesTargetVoxel, ...
    'orientation', tesTargetOrientation, ...
    'targetRadiusMm', 2, ...
    'activeElectrodeCount', cfg.nTes, ...
    'totalCurrentMa', cfg.tesTotalCurrentMa, ...
    'maxCurrentPerElectrodeMa', cfg.tesMaxCurrentPerElectrodeMa, ...
    'optType', 'wls-l1per', ...
    'desiredIntensityVm', 0.5, ...
    'focalityK', 0.005, ...
    'searchMode', leadFieldSearchMode, ...
    'excludedElectrodeNames', sparseExcludedNames16, ...
    'targetingTag', sprintf('%s_lf%d_tes%d', ...
    cfg.leadFieldDesignTag, cfg.nInitialCandidates, cfg.nTes), ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures);

fieldQc16 = acsVisualizeSparseRoastLeadField(sparse16, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures);

%% 09 - Grow candidate layout with surrogate lead fields
% Slow: by default only the final exact lead field is expensive. Intermediate
% growth uses approximate/surrogate-expanded lead fields.
% Output: finalCandidateLayout, finalLeadField, and finalSparse.

if ~any(strcmpi(cfg.growthLeadFieldMode, {'surrogateExpanded', 'fullRoast'}))
    error('exampleWalkthrough:BadGrowthLeadFieldMode', ...
        'cfg.growthLeadFieldMode must be surrogateExpanded or fullRoast.');
end

targetOptsGrow = targetOptsBase;
targetOptsGrow.edgeMarginMM = 5;
targetOptsGrow.midlineMarginMM = 5;
targetOptsGrow.vizSurfaceGeodesic = cfg.showFigures;

candidateGrowth = struct([]);
currentCandidateCount = cfg.nInitialCandidates;
currentLayout = layout16;
currentLeadField = lf16;
currentSparse = sparse16;
successfulGrowthSteps = 0;
growthStoppedEarly = false;
growthStopReason = '';

for g = 1:cfg.nGrowthSteps
    nextCandidateCount = currentCandidateCount + cfg.nNewCandidates;
    growthTag = sprintf('grow%dto%d_%s_v%02d', ...
        currentCandidateCount, nextCandidateCount, ...
        cfg.leadFieldDesignTag, g);
    fprintf('\nCandidate growth step %d/%d: %d -> %d candidates\n', ...
        g, cfg.nGrowthSteps, currentCandidateCount, nextCandidateCount);

    try
        candidateGrowth(g).proposal = acsProposeRoastCandidateGrowth( ...
            currentLayout, currentSparse, ...
            'nNew', cfg.nNewCandidates, ...
            'poolSize', 128, ...
            'acquisitionMode', cfg.growthAcquisitionMode, ...
            'ucbBeta', cfg.growthUcbBeta, ...
            'ucbUncertaintyMode', cfg.growthUcbUncertaintyMode, ...
            'excludeBedClippedCandidates', true, ...
            'excludeBadNormalCandidates', true, ...
            'holderMinBedClearanceMm', 1.0, ...
            'holderNormalMode', cfg.holderNormalMode, ...
            'holderSmoothNormalRadiusMm', cfg.holderSmoothNormalRadiusMm, ...
            'holderNormalDeviationThresholdDeg', ...
                cfg.holderNormalDeviationThresholdDeg, ...
            'holderMinAxisZ', cfg.placementNormalUpDotMin, ...
            'holderMaxRawToSmoothNormalAngleDeg', ...
                cfg.holderMaxRawToSmoothNormalAngleDeg, ...
            'zBedMm', 0, ...
            'proposalTag', growthTag, ...
            'targetOptions', targetOptsGrow, ...
            'earExclusionMode', cfg.earEditMode, ...
            'earExclusionFile', activeEarExclusionFile, ...
            'strapExclusionMode', cfg.strapExclusionMode, ...
            'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
            'strapWidthMm', cfg.strapWidthMm, ...
            'strapMarginMm', cfg.strapMarginMm, ...
            'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
            'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
            'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
            'makeLayout', true, ...
            'forceLayout', force.layoutProducts, ...
            'showFigures', cfg.showFigures, ...
            'saveFigures', cfg.saveFigures);
    catch ME
        if any(strcmp(ME.identifier, { ...
                'acsProposeRoastCandidateGrowth:TooFewVirtualCandidates', ...
                'acsProposeRoastCandidateGrowth:TooFewScoredCandidates', ...
                'acsProposeRoastCandidateGrowth:NoCandidateVertices'}))
            growthStoppedEarly = true;
            growthStopReason = ME.message;
            warning('exampleWalkthrough:CandidateGrowthStopped', ...
                ['Stopping growth early: %s\nContinuing with the ', ...
                 'current %d-candidate layout.'], ...
                ME.message, currentCandidateCount);
            break;
        end
        rethrow(ME);
    end

    candidateGrowth(g).layout = candidateGrowth(g).proposal.expandedLayout;
    candidateGrowth(g).siteValidity = acsEvaluateCapMakerManufacturingSites( ...
        candidateGrowth(g).layout, ...
        'strapExclusionMode', cfg.strapExclusionMode, ...
        'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
        'strapWidthMm', cfg.strapWidthMm, ...
        'strapMarginMm', cfg.strapMarginMm, ...
        'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
        'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
        'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
        'holderNormalMode', cfg.holderNormalMode, ...
        'holderSmoothNormalRadiusMm', cfg.holderSmoothNormalRadiusMm, ...
        'holderNormalDeviationThresholdDeg', ...
            cfg.holderNormalDeviationThresholdDeg, ...
        'holderMinAxisZ', cfg.placementNormalUpDotMin, ...
        'holderMaxRawToSmoothNormalAngleDeg', ...
            cfg.holderMaxRawToSmoothNormalAngleDeg, ...
        'showFigures', false, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
    excludedThisStep = candidateGrowth(g).siteValidity.invalidNames(:);

    if cfg.useDummyLeadFields
        candidateGrowth(g).leadField = acsGenerateDummyRoastLeadField( ...
            candidateGrowth(g).layout, ...
            'simulationTag', sprintf('DUMMY_%s_capMakerGeo_lf%d_%s', ...
            cfg.subjectId, nextCandidateCount, cfg.leadFieldDesignTag), ...
            'force', true);
    elseif strcmpi(cfg.growthLeadFieldMode, 'surrogateExpanded')
        candidateGrowth(g).leadField = ...
            acsGenerateApproximateExpandedRoastLeadField( ...
            currentLayout, currentLeadField, candidateGrowth(g).layout, ...
            'simulationTag', sprintf( ...
            '%s_capMakerGeo_lf%d_%s_surrogateGrow%02d', ...
            cfg.subjectId, nextCandidateCount, ...
            cfg.leadFieldDesignTag, g), ...
            'kernelSigmaMm', 'auto', ...
            'referenceElectrode', currentLeadField.referenceElectrode, ...
            'force', force.layoutProducts, ...
            'verbose', true);
    else
        candidateGrowth(g).leadField = acsGenerateRoastLeadField( ...
            candidateGrowth(g).layout, ...
            'simulationTag', sprintf('%s_capMakerGeo_lf%d_%s_biosemiGel01', ...
            cfg.subjectId, nextCandidateCount, cfg.leadFieldDesignTag), ...
            'referenceElectrode', currentLeadField.referenceElectrode, ...
            'electrodeModel', 'biosemiPin', ...
            'segMaskFile', mainSegMaskFile, ...
            'extraTissues', mainExtraTissues, ...
            'conductivities', mainConductivities, ...
            'resampling', 'off', ...
            'roastOptions', electricFieldVisualizationOptions, ...
            'execute', cfg.executeLeadFieldSolves, ...
            'saveReport', cfg.saveLeadFieldRequestReports);
    end

    candidateGrowth(g).sparse = acsOptimizeSparseRoastLeadField( ...
        candidateGrowth(g).layout.t1File, ...
        candidateGrowth(g).leadField.simulationTag, ...
        tesTargetVoxel, ...
        'orientation', tesTargetOrientation, ...
        'targetRadiusMm', 2, ...
        'activeElectrodeCount', cfg.nTes, ...
        'totalCurrentMa', cfg.tesTotalCurrentMa, ...
        'maxCurrentPerElectrodeMa', cfg.tesMaxCurrentPerElectrodeMa, ...
        'optType', 'wls-l1per', ...
        'desiredIntensityVm', 0.5, ...
        'focalityK', 0.005, ...
        'searchMode', leadFieldSearchMode, ...
        'excludedElectrodeNames', excludedThisStep, ...
        'targetingTag', sprintf('%s_lf%d_tes%d', ...
        cfg.leadFieldDesignTag, nextCandidateCount, cfg.nTes), ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures);

    currentCandidateCount = nextCandidateCount;
    currentLayout = candidateGrowth(g).layout;
    currentLeadField = candidateGrowth(g).leadField;
    currentSparse = candidateGrowth(g).sparse;
    successfulGrowthSteps = successfulGrowthSteps + 1;
end

finalSiteValidity = acsEvaluateCapMakerManufacturingSites(currentLayout, ...
    'strapExclusionMode', cfg.strapExclusionMode, ...
    'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
    'strapWidthMm', cfg.strapWidthMm, ...
    'strapMarginMm', cfg.strapMarginMm, ...
    'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
    'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
    'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
    'holderNormalMode', cfg.holderNormalMode, ...
    'holderSmoothNormalRadiusMm', cfg.holderSmoothNormalRadiusMm, ...
    'holderNormalDeviationThresholdDeg', cfg.holderNormalDeviationThresholdDeg, ...
    'holderMinAxisZ', cfg.placementNormalUpDotMin, ...
    'holderMaxRawToSmoothNormalAngleDeg', ...
        cfg.holderMaxRawToSmoothNormalAngleDeg, ...
    'showFigures', false, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);
finalExcludedTesElectrodeNames = finalSiteValidity.invalidNames(:);

hasApproximateLeadField = isstruct(currentLeadField) && ...
    isfield(currentLeadField, 'approximate') && currentLeadField.approximate;
if cfg.runExactFinalLeadFieldAfterGrowth && ~cfg.useDummyLeadFields && ...
        strcmpi(cfg.growthLeadFieldMode, 'surrogateExpanded') && ...
        successfulGrowthSteps > 0 && hasApproximateLeadField
    finalApproxLeadField = currentLeadField;
    finalApproxSparse = currentSparse;
    finalExactLeadFieldTag = sprintf( ...
        '%s_capMakerGeo_lf%d_%s_biosemiGel01_finalExact', ...
        cfg.subjectId, currentCandidateCount, cfg.leadFieldDesignTag);
    fprintf('\nRunning final exact ROAST lead field for %d candidates.\n', ...
        currentCandidateCount);
    try
        currentLeadField = acsGenerateRoastLeadField(currentLayout, ...
            'simulationTag', finalExactLeadFieldTag, ...
            'referenceElectrode', finalApproxLeadField.referenceElectrode, ...
            'electrodeModel', 'biosemiPin', ...
            'segMaskFile', mainSegMaskFile, ...
            'extraTissues', mainExtraTissues, ...
            'conductivities', mainConductivities, ...
            'resampling', 'off', ...
            'roastOptions', electricFieldVisualizationOptions, ...
            'execute', cfg.executeLeadFieldSolves, ...
            'saveReport', cfg.saveLeadFieldRequestReports);
        currentSparse = acsOptimizeSparseRoastLeadField(currentLayout.t1File, ...
            currentLeadField.simulationTag, ...
            tesTargetVoxel, ...
            'orientation', tesTargetOrientation, ...
            'targetRadiusMm', 2, ...
            'activeElectrodeCount', cfg.nTes, ...
            'totalCurrentMa', cfg.tesTotalCurrentMa, ...
            'maxCurrentPerElectrodeMa', cfg.tesMaxCurrentPerElectrodeMa, ...
            'optType', 'wls-l1per', ...
            'desiredIntensityVm', 0.5, ...
            'focalityK', 0.005, ...
            'searchMode', leadFieldSearchMode, ...
            'excludedElectrodeNames', finalExcludedTesElectrodeNames, ...
            'targetingTag', sprintf('%s_lf%d_tes%d_finalExact', ...
            cfg.leadFieldDesignTag, currentCandidateCount, cfg.nTes), ...
            'showFigures', cfg.showFigures, ...
            'saveFigures', cfg.saveFigures);
    catch ME
        warning('exampleWalkthrough:FinalExactLeadFieldFailed', ...
            ['Final exact lead field failed: %s\nKeeping the ', ...
             'surrogate-expanded final state.'], ME.message);
        currentLeadField = finalApproxLeadField;
        currentSparse = finalApproxSparse;
    end
end

finalCandidateCount = currentCandidateCount;
finalCandidateLayout = currentLayout;
finalLeadField = currentLeadField;
finalSparse = currentSparse;
finalSparse.recipe

%% 10 - Optional tES channel-count sweep
% Analysis only: this does not change the manufactured cap recipe. It asks
% whether a larger active-channel budget gives meaningful targeting gains.

tesChannelSweepSparse = {};
tesChannelSweepTable = table();
tesChannelSweepRecommendation = struct();
if cfg.runTesChannelCountSweep
    finalNames = finalCandidateLayout.names(:);
    selectableForSweep = ~ismember(lower(string(finalNames)), ...
        lower(string(finalExcludedTesElectrodeNames)));
    maxSweepCount = nnz(selectableForSweep);
    sweepCounts = unique([cfg.tesChannelSweepCounts(:); cfg.nTes]);
    sweepCounts = sweepCounts(sweepCounts >= 4 & mod(sweepCounts, 2) == 0 & ...
        sweepCounts <= maxSweepCount);

    nSweep = numel(sweepCounts);
    tesChannelSweepSparse = cell(nSweep, 1);
    requestedCount = zeros(nSweep, 1);
    effectiveCount = zeros(nSweep, 1);
    objectiveVm = zeros(nSweep, 1);
    totalAbsCurrentMa = zeros(nSweep, 1);
    selectedNamesByCount = cell(nSweep, 1);

    for kIdx = 1:nSweep
        kTes = sweepCounts(kIdx);
        tesChannelSweepSparse{kIdx} = acsOptimizeSparseRoastLeadField( ...
            finalCandidateLayout.t1File, ...
            finalLeadField.simulationTag, ...
            tesTargetVoxel, ...
            'orientation', tesTargetOrientation, ...
            'targetRadiusMm', 2, ...
            'activeElectrodeCount', kTes, ...
            'totalCurrentMa', cfg.tesTotalCurrentMa, ...
            'maxCurrentPerElectrodeMa', cfg.tesMaxCurrentPerElectrodeMa, ...
            'optType', 'wls-l1per', ...
            'desiredIntensityVm', 0.5, ...
            'focalityK', 0.005, ...
            'searchMode', leadFieldSearchMode, ...
            'excludedElectrodeNames', finalExcludedTesElectrodeNames, ...
            'targetingTag', sprintf('%s_lf%d_tesSweep%02d', ...
            cfg.leadFieldDesignTag, finalCandidateCount, kTes), ...
            'showFigures', false, ...
            'saveFigures', false, ...
            'verbose', true);

        s = tesChannelSweepSparse{kIdx};
        absCurr = abs(s.currentsMa(:));
        thresholdMa = max(cfg.tesChannelSweepEffectiveCurrentThresholdMa, ...
            cfg.tesChannelSweepEffectiveCurrentFraction * max(absCurr));
        requestedCount(kIdx) = kTes;
        effectiveCount(kIdx) = nnz(absCurr >= thresholdMa);
        objectiveVm(kIdx) = s.objectiveVm;
        totalAbsCurrentMa(kIdx) = sum(absCurr);
        selectedNamesByCount{kIdx} = s.selectedNames(:);
    end

    bestSoFarObjectiveVm = cummax(objectiveVm);
    bestObjectiveVm = max(bestSoFarObjectiveVm);
    plateauRows = find(bestSoFarObjectiveVm >= ...
        cfg.tesChannelSweepPlateauFractionOfBest * bestObjectiveVm);
    recommendedTesCount = NaN;
    if ~isempty(plateauRows)
        recommendedTesCount = requestedCount(plateauRows(1));
    end

    tesChannelSweepTable = table(requestedCount, effectiveCount, ...
        objectiveVm, bestSoFarObjectiveVm, totalAbsCurrentMa, ...
        selectedNamesByCount, ...
        'VariableNames', {'requestedTesCount', 'effectiveActiveCount', ...
        'objectiveVm', 'bestSoFarObjectiveVm', 'totalAbsCurrentMa', ...
        'selectedNames'});
    tesChannelSweepRecommendation = struct( ...
        'recommendedTesCount', recommendedTesCount, ...
        'bestObjectiveVm', bestObjectiveVm, ...
        'plateauFractionOfBest', cfg.tesChannelSweepPlateauFractionOfBest);
    disp(tesChannelSweepTable);

    sweepTag = regexprep(sprintf('%s_%s_lf%d', ...
        cfg.subjectId, cfg.leadFieldDesignTag, finalCandidateCount), ...
        '[^\w-]', '_');
    tesChannelSweepReportMat = fullfile(P.capWorkFolder, ...
        [sweepTag '_tesChannelSweep.mat']);
    save(tesChannelSweepReportMat, 'tesChannelSweepSparse', ...
        'tesChannelSweepTable', 'tesChannelSweepRecommendation');
end

%% 11 - Visualize the final tES field and assemble tES+EEG layout
% Interactive: no.
% Output: field QC, combined tES+EEG layout, and a printable wiring map.

finalFieldQc = acsVisualizeSparseRoastLeadField(finalSparse, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures);

eegTargetOpts = targetOptsBase;
eegTargetOpts.placementMode = 'surfaceVoronoi';
eegTargetOpts.preferSymmetry = false;
eegTargetOpts.midlineMarginMM = 0;
eegTargetOpts.voronoiIterations = 10;
eegTargetOpts.voronoiSnapMode = 'spacingAware';
eegTargetOpts.voronoiSpacingWeight = 4;
eegTargetOpts.voronoiMinSpacingFraction = 0.75;
eegTargetOpts.voronoiSpacingIterations = 3;
eegTargetOpts.vizSurfaceVoronoi = cfg.showFigures;
eegTargetOpts.vizSurfaceGeodesic = false;

combinedLayout = acsAssembleTesEegCapMakerLayout( ...
    finalCandidateLayout, finalSparse, ...
    'nTes', cfg.nTes, ...
    'nEeg', cfg.nEeg, ...
    'eegPreferSymmetry', false, ...
    'eegMidlineMarginMM', 0, ...
    'eegExclusionRadiusMm', 12, ...
    'eegTargetOptions', eegTargetOpts, ...
    'skinCacheFile', skinCacheForManufacturing, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', activeEarExclusionFile, ...
    'strapExclusionMode', cfg.strapExclusionMode, ...
    'strapRostralOffsetMm', cfg.strapRostralOffsetMm, ...
    'strapWidthMm', cfg.strapWidthMm, ...
    'strapMarginMm', cfg.strapMarginMm, ...
    'strapExclusionRadiusMm', cfg.strapExclusionRadiusMm, ...
    'strapLateralLengthMm', cfg.strapLateralLengthMm, ...
    'strapSampleSpacingMm', cfg.strapSampleSpacingMm, ...
    'forceLayout', force.layoutProducts, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

layoutPrintoutFile = fullfile(P.capWorkFolder, sprintf( ...
    '%s_%s_tes%d_eeg%d_layoutPrintout.pdf', ...
    cfg.subjectId, cfg.capDesignTag, cfg.nTes, cfg.nEeg));
capLayoutPrintout = acsMakeCapLayoutPrintout(combinedLayout, ...
    'outputFile', layoutPrintoutFile, ...
    'footprintSource', 'skinCache', ...
    'skinCacheFile', skinCacheForManufacturing, ...
    'footprintMeshStage', 'fullHead', ...
    'titleText', sprintf('%s %s tES/EEG cap layout', ...
    cfg.subjectId, cfg.capDesignTag), ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 12 - Optional EEG artifact prediction from the tES recipe
% Slow: can run a direct ROAST solve depending on cache and flags.
% Output: predicted EEG-channel voltage table and topography.

if cfg.runEegPrediction
    tesRecipe = finalSparse.recipe;
    eegPrediction = acsPredictEegVoltagesFromTes(combinedLayout, tesRecipe, ...
        'simulationTag', sprintf('%s_tes%d_eeg%d_%s_voltageCheck', ...
        cfg.subjectId, cfg.nTes, cfg.nEeg, cfg.leadFieldDesignTag), ...
        'forceModel', false, ...
        'forceDirectSolve', false, ...
        'execute', cfg.executeLeadFieldSolves, ...
        'electrodeModel', 'biosemiPin', ...
        'resampling', 'off', ...
        'roastOptions', mainRoastExtraOptions, ...
        'sampleDomain', 'electrode', ...
        'referenceMode', 'meanEeg', ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'showTopography', cfg.showFigures, ...
        'saveTopography', cfg.saveFigures, ...
        'topographyOptions', { ...
            'valueMode', 'referencedMicroV', ...
            'interpolation', 'rbf', ...
            'showTes', true}, ...
        'verbose', true);
    eegPrediction.eegTable
end

%% 13 - Preview/tune chin strap parameters
% Interactive: optional. Leave cfg.runChinStrapPreview=false to skip.
% Output: strapCorr* variables consumed by manufacturing cells.

manufacturingVoxelSizeMm = 0.75;
strapCorrAmpMm = 2.0;
strapCorrPitchMm = 7.0;
strapCorrStyle = 'rectilinear';
strapCorrFitIntegerCycles = true;
strapPreviewOutputDir = fullfile(repoRoot, 'outputs', 'debug', ...
    'chinStrapPreview');
strapParameterFile = fullfile(strapPreviewOutputDir, ...
    [manufacturingTag '_chinStrapParams.mat']);

if exist(strapParameterFile, 'file') == 2
    strapSaved = load(strapParameterFile, 'strapPreviewOptions');
    if isfield(strapSaved, 'strapPreviewOptions')
        strapCorrAmpMm = strapSaved.strapPreviewOptions.strapCorrAmpMm;
        strapCorrPitchMm = strapSaved.strapPreviewOptions.strapCorrPitchMm;
        strapCorrStyle = strapSaved.strapPreviewOptions.strapCorrStyle;
        strapCorrFitIntegerCycles = ...
            strapSaved.strapPreviewOptions.strapCorrFitIntegerCycles;
    end
end

if cfg.runChinStrapPreview
    clear acsPreviewChinStrapGeometry strapFn_world corrStrapLocalMask
    chinStrapPreview = acsPreviewChinStrapGeometry( ...
        'outputDir', strapPreviewOutputDir, ...
        'previewTag', [manufacturingTag '_chinStrap'], ...
        'parameterFile', strapParameterFile, ...
        'voxelSizeMm', manufacturingVoxelSizeMm, ...
        'strapCorrAmpMm', strapCorrAmpMm, ...
        'strapCorrPitchMm', strapCorrPitchMm, ...
        'strapCorrStyle', strapCorrStyle, ...
        'strapCorrFitIntegerCycles', strapCorrFitIntegerCycles, ...
        'interactive', true, ...
        'showFigures', true, ...
        'saveFigures', false, ...
        'verbose', true);
end

%% 14 - Preflight manufacturing geometry
% Interactive: no.
% Output: QC figure and report, but no final STL export.

implantExclusionFiles = {headpostExclusionFile; chamberExclusionFile};
manufacturingRailEdgeMarginMm = 0;
holeBoreClearanceMm = 0.1;
holeScalpFlareDiaMm = 5.5;
holeScalpClearanceMm = 0.25;
holeScalpExtendMm = 6;

manufacturingCommonArgs = { ...
    'manufacturingTag', manufacturingTag, ...
    'skinCacheFile', skinCacheForManufacturing, ...
    'implantExclusionFile', implantExclusionFiles, ...
    'implantRailExclusionMode', 'projectedPolys', ...
    'implantElectrodePolicy', 'warn', ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', activeEarExclusionFile, ...
    'earElectrodePolicy', 'error', ...
    'railEarExclusionMode', 'sphere3d', ...
    'railEdgeMarginMm', manufacturingRailEdgeMarginMm, ...
    'strapMode', 'earRostral', ...
    'strapCorrAmpMm', strapCorrAmpMm, ...
    'strapCorrPitchMm', strapCorrPitchMm, ...
    'strapCorrStyle', strapCorrStyle, ...
    'strapCorrFitIntegerCycles', strapCorrFitIntegerCycles, ...
    'holderSupportMode', 'nearestRail', ...
    'holderSupportCount', 2, ...
    'holderSupportMinAngleDeg', 90, ...
    'holderSupportRespectEarExclusions', false, ...
    'holderSupportRespectImplantExclusions', true, ...
    'holderBridgeMode', 'auto', ...
    'holeKeepoutMode', 'flared', ...
    'holeBoreClearanceMm', holeBoreClearanceMm, ...
    'holeScalpFlareDiaMm', holeScalpFlareDiaMm, ...
    'holeScalpClearanceMm', holeScalpClearanceMm, ...
    'holeScalpExtendMm', holeScalpExtendMm, ...
    'fuseCloseVox', 1, ...
    'carveCloseVox', 0, ...
    'preserveFusedTpeOccupancy', true, ...
    'holderBedClearancePolicy', 'warn', ...
    'holderMinBedClearanceMm', 1.0, ...
    'holderPlacementSurfaceMode', 'full', ...
    'holderNormalMode', cfg.holderNormalMode, ...
    'holderSmoothNormalRadiusMm', cfg.holderSmoothNormalRadiusMm, ...
    'holderNormalDeviationThresholdDeg', ...
        cfg.holderNormalDeviationThresholdDeg, ...
    'strapElectrodePolicy', 'warn', ...
    'manufacturingSurfaceMaxFaces', 5000, ...
    'railSurfaceMaxFaces', 5000, ...
    'qcMaxFaces', 5000, ...
    'showQcLabels', true, ...
    'voxelSizeMm', manufacturingVoxelSizeMm, ...
    'saveMeshMat', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true};

manufacturingPreflight = acsBuildCapMakerManufacturingStl(combinedLayout, ...
    manufacturingCommonArgs{:}, ...
    'preflightOnly', true, ...
    'force', true);

%% 15 - Build final TPE/PLA STLs
% Slow: voxel booleans and STL export can take time.
% Output: TPE and PLA STL files for slicing/printing.

manufacturing = acsBuildCapMakerManufacturingStl(combinedLayout, ...
    manufacturingCommonArgs{:}, ...
    'preflightOnly', false, ...
    'minFinalTpeComponentVoxels', 80, ...
    'minFinalPlaComponentVoxels', 80, ...
    'force', force.manufacturing);

manufacturing.tpeStlFile
manufacturing.plaStlFile

%% 16 - Inspect final manufacturing geometry
% Interactive: yes, this is the best final visual check before slicing.

manufacturingInspector = acsInspectCapMakerManufacturingGeometry(manufacturing, ...
    'skinAlpha', 0.28, ...
    'capAlpha', 0.42, ...
    'plaAlpha', 0, ...
    'holderAlpha', 0.92, ...
    'smoothNormalRadiusMm', 6, ...
    'warnNormalAngleDeg', 25, ...
    'badNormalAngleDeg', 45, ...
    'undersideAxisZThreshold', cfg.placementNormalUpDotMin, ...
    'showLabels', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

if cfg.runChinStrapDiagnostics
    chinStrapDiagnostics = acsDiagnoseChinStrapManufacturing(manufacturing, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
end
