%% NHPulse Synthetic Example Walkthrough
% This public-facing walkthrough creates tiny synthetic, ROAST-ready anatomy
% and exercises the main NHPulse workflow: canonical scalp extraction,
% printer-bed cropping, ear/face exclusions, implant placement, a PLA
% fit-check scaffold, fiducial bookkeeping, target selection, dummy or ROAST
% leadfield-based tES
% layout growth, EEG interleaving, and dual-material cap STL export.
%
% The synthetic head is intentionally cartoon-like. It is useful for checking
% installation, file formats, coordinate plumbing, and cap-layout code paths;
% it is not anatomically realistic and should not be used for scientific
% simulation claims.
%
% ROAST credit: NHPulse builds on ROAST. Please cite ROAST and the relevant
% papers listed in CITATION.md when using this code.
%
% Safety note: this is research software, not a medical device.

%% 00 - Configure MATLAB Path And Demo Settings
% Run this cell from the repository root.

% clear;  % Uncomment when intentionally starting a clean MATLAB session.
% clc;

repoRoot = fileparts(mfilename('fullpath'));
if isempty(repoRoot)
    repoRoot = pwd;
end

setNHPulsePath('repoRoot', repoRoot);
P = acsPaths();
if isempty(P.configFile)
    fprintf(['No local.paths.json found; using default repo-local outputs.\n', ...
        'Run nhpulseConfigureLocalPaths if you want to save machine-specific paths.\n']);
end

% The preset owns the long list of demo settings. Use syntheticFast for a
% deterministic noninteractive dummy-leadfield run, or syntheticRoast to run
% actual ROAST/GetDP solves on the toy head.
cfg = nhpulseExampleConfig('syntheticReviewer');

% Common reviewer overrides:
% cfg = nhpulseExampleConfig('syntheticFast', 'showFigures', false);
% cfg = nhpulseExampleConfig('syntheticRoast');
% cfg.force = false;  % Reuse cached selections/products after a first pass.

fprintf('NHPulse synthetic walkthrough output:\n  %s\n', cfg.outputDir);
nhpulseEnsureWritableDir(cfg.outputDir, 'synthetic walkthrough output');
restoreFigureWindowStyle = setTemporaryFigureWindowStyle('normal');

%% 01 - Create Synthetic ROAST-Ready Anatomy
% Objective: create non-sensitive toy anatomy that behaves like the file
% products expected by the real workflow. Reviewers can test coordinate
% plumbing, mesh extraction, and cap geometry without private animal data.
%
% This creates:
%   *_T1.nii
%   *_T1_T1orT2_SPM_masks.nii
%   synthetic model/phone fiducials
%   a synthetic phone-scan-like PLY/MAT surface
%
% The returned struct has syntheticOut.roastReady, which is the smallest
% useful public entry point into the NHPulse pipeline.

syntheticOut = nhpulseCreateSyntheticRoastReadyData(cfg.outputDir, ...
    'subjectId', cfg.subjectId, ...
    'force', cfg.force, ...
    'showFigure', cfg.showFigures, ...
    'saveFigure', cfg.saveFigures);

disp(syntheticOut.roastReady)
[roastFolder, t1Stem] = fileparts(syntheticOut.t1File);

%% 02 - Build A ROAST-Derived Full-Head Scalp Mesh Cache
% Objective: establish the scalp surface used by capMaker/manufacturing steps.
% In real work this is the geometry that may later be updated with phone scans
% or digitizer traces, and it should remain the common surface for cap layout.
%
% NHPulse uses a single canonical scalp surface for the capMaker side of the
% pipeline. For real data this can later be warped to phone/LiDAR or digitizer
% traces; this synthetic example keeps the ROAST-derived mesh unchanged.

fullHeadScalpCacheFile = fullfile(cfg.outputDir, ...
    sprintf('%s_roastScalpSkinMesh.mat', cfg.subjectId));

fullHeadScalp = acsBuildRoastScalpSkinCache(syntheticOut, ...
    'outputFile', fullHeadScalpCacheFile, ...
    'force', cfg.force, ...
    'maxFaces', 8000, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

fprintf('Full-head scalp cache mesh: %d vertices, %d faces\n', ...
    fullHeadScalp.meshStats.nVertices, fullHeadScalp.meshStats.nFaces);

%% 03 - Crop The Scalp To The Printable Cap Footprint
% Objective: decide what portion of the head should be eligible for cap
% material. The crop plane becomes the 3D-printer bed (Z=0), and rubber/TPE cap
% mesh is built only over scalp points above that plane. Later steps add
% margins around the crop edge and local exclusions for ears, face, and
% implants.
%
% The capMaker manufacturing frame has Z=0 at the printer-bed/crop plane. The
% GUI is seeded with a deterministic synthetic crop plane. Use it as-is or
% adjust it to practice the manual crop workflow.

capSkinCacheFile = fullfile(cfg.outputDir, ...
    sprintf('%s_printerBedSkinMesh.mat', cfg.subjectId));
cropPlaneFile = fullfile(cfg.outputDir, ...
    sprintf('%s_printerBedCropPlane.mat', cfg.subjectId));

cropMode = chooseMode(cfg.interactiveSelections, 'select', 'auto');
capSkin = acsCropWarpedSkinCacheToPrinterBed(fullHeadScalp.cacheFile, ...
    'outputFile', capSkinCacheFile, ...
    'cropPlaneFile', cropPlaneFile, ...
    'cropPlaneMode', cropMode, ...
    'cropSide', 'top', ...
    'initialCropAxis', cfg.syntheticCropAxis, ...
    'initialCropDistance', cfg.syntheticCropDistanceMm, ...
    'skinMaxFaces', 1200, ...
    'keepLargestSkinComponent', true, ...
    'force', cfg.force, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

fprintf('Printable scalp cache mesh: %d vertices, %d faces\n', ...
    capSkin.meshStats.skin.nVertices, capSkin.meshStats.skin.nFaces);

%% 04 - Define Ear And Painted Manufacturing Exclusions
% Objective: mark local regions that should not receive cap material even if
% they are above the crop plane. Use ear spheres for ears and painted vertices
% for face/eyelid/other local areas that should not become rail endpoints or
% electrode sites.
%
% Ear exclusions keep electrodes and cap rails away from sensitive/highly
% curved regions. With cfg.interactiveSelections=true, the GUI opens so the
% user can practice moving the ear spheres and painting additional face/skin
% vertices. Set the flag false for deterministic auto proposals.

earExclusionFile = fullfile(cfg.outputDir, ...
    sprintf('%s_printerBedEarExclusions.mat', cfg.subjectId));
earEditMode = chooseMode(cfg.interactiveSelections, 'always', 'auto');

earExclusions = acsSelectEarExclusionSpheres(capSkin.cacheFile, ...
    'outputFile', earExclusionFile, ...
    'force', cfg.force, ...
    'editMode', earEditMode, ...
    'showFigures', cfg.interactiveSelections, ...
    'saveFigures', cfg.saveFigures, ...
    'showVertexOverlay', true, ...
    'showStrapPreview', true, ...
    'verbose', true);

%% 05 - Place A Synthetic Headpost And Build Its Cap Keepout
% Objective: represent cranial implant geometry. Many neurophysiology animals
% have titanium headposts, chambers, or similar implants. Cap manufacturing
% should avoid exposed implant regions, and optional electrical models may
% include implant conductivity.
%
% Real workflows can pass a Polhemus/phone-scan-derived implant trace here.
% The synthetic walkthrough creates a circular trace, places the simplified
% headpost STL, and then derives the tight cylindrical keepout used by cap
% layout/manufacturing.

headpostTraceFile = fullfile(cfg.outputDir, ...
    sprintf('%s_syntheticHeadpostTrace.mat', cfg.subjectId));
headpostTrace = nhpulseCreateSyntheticHeadpostTrace(capSkin.cacheFile, ...
    'outputFile', headpostTraceFile, ...
    'radiusMm', cfg.demoHeadpostRadiusMm, ...
    'nPoints', 72, ...
    'showFigure', cfg.showFigures, ...
    'saveFigure', cfg.saveFigures, ...
    'verbose', true);

headpostPlacementFile = fullfile(cfg.outputDir, ...
    sprintf('%s_headpostPlacement.mat', cfg.subjectId));
headpostPlacement = acsPlanHeadpostPlacement(headpostTrace, capSkin.cacheFile, ...
    'maskFile', syntheticOut.maskFile, ...
    'meshScale', cfg.demoHeadpostScale, ...
    'interactive', cfg.interactiveSelections, ...
    'outputFile', headpostPlacementFile, ...
    'force', cfg.force, ...
    'reuseExistingPose', true, ...
    'bendStraps', true, ...
    'bendThicknessMode', 'skullNormal', ...
    'headpostRefineMaxEdgeMm', 4, ...
    'headpostRefineMaxIterations', 2, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

headpostExclusionFile = fullfile(cfg.outputDir, ...
    sprintf('%s_headpostKeepout.mat', cfg.subjectId));
headpostExclusion = acsMakeHeadpostExclusionFromPlacement( ...
    headpostPlacement, capSkin.cacheFile, ...
    'outputFile', headpostExclusionFile, ...
    'marginMm', cfg.headpostMarginMm, ...
    'footprintMode', 'postCylinder', ...
    'force', cfg.force, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 06 - Export A Fast PLA Fit-Check STL
% Objective: create a fast physical shape check before a long dual-material
% print. The sparse PLA scaffold tests the cropped scalp shape and keepouts
% without committing to the full TPE cap geometry.
%
% A sparse PLA scaffold is useful for gross fit checks before committing to a
% full TPE-on-PLA print. This scaffold uses a toy marker layout and the same
% ear/painted/headpost manufacturing keepouts used by the final cap.

fitCheckCustomLocationsFile = fullfile(roastFolder, ...
    [t1Stem '_fitCheckCustomLocations']);

fitCheckTargetOptions = baseCapTargetOptions(cfg);
fitCheckTargetOptions = addHeadpostKeepout( ...
    fitCheckTargetOptions, headpostExclusion);

fitCheckLayout = acsMakeRoastCapMakerLayout(syntheticOut, ...
    'surfaceSource', 'capMaker', ...
    'subjectId', cfg.subjectId, ...
    'skinCacheFile', capSkin.cacheFile, ...
    'nElectrodes', cfg.fitCheckElectrodes, ...
    'outputFile', fitCheckCustomLocationsFile, ...
    'targetOptions', fitCheckTargetOptions, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', earExclusionFile, ...
    'strapExclusionMode', 'auto', ...
    'forceLayout', cfg.force, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

fitCheckDir = fullfile(cfg.outputDir, 'fitChecks', ...
    sprintf('%s_sparsePlaFitCheck', cfg.subjectId));

fitCheck = acsBuildCapMakerFitCheckStl(fitCheckLayout, ...
    'skinCacheFile', capSkin.cacheFile, ...
    'outputDir', fitCheckDir, ...
    'fitCheckTag', sprintf('%s_sparsePlaFitCheck', cfg.subjectId), ...
    'force', cfg.force, ...
    'includeElectrodeMarkers', true, ...
    'gridSurfaceMaxFaces', cfg.fitCheckGridSurfaceMaxFaces, ...
    'railEdgeMarginMm', 2, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', earExclusionFile, ...
    'earRailExclusionGeometry', 'sphere3d', ...
    'implantExclusionFile', {headpostExclusionFile}, ...
    'componentCleanupMode', 'largest', ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

fprintf('Synthetic fit-check STL:\n  %s\n', fitCheck.stlFile);

%% 07 - Mark Or Reuse Model Fiducials
% Objective: define landmarks that let MRI, digitizer traces, phone scans, and
% other measurements share a reference frame.
%
% Fiducials are used for registering digitizer/scan data to MRI/capMaker
% space. The synthetic generator already knows the matching locations. Set
% cfg.interactiveSelections=true to practice selecting them on the mesh.

fiducialLabels = {'Nas', 'Lpa', 'Rpa', 'Ini'};
modelFiducialsFile = fullfile(cfg.outputDir, ...
    sprintf('%s_modelFiducialsOnScalp.mat', cfg.subjectId));

if cfg.interactiveSelections
    modelFiducials = acsSelectModelFiducials(fullHeadScalp.cacheFile, ...
        'fiducialLabels', fiducialLabels, ...
        'meshStage', 'fullHead', ...
        'outputFile', modelFiducialsFile, ...
        'force', cfg.force, ...
        'editMode', 'always', ...
        'showFigures', true, ...
        'saveFigures', cfg.saveFigures, ...
        'verbose', true);
else
    modelFiducials = syntheticOut.modelFiducials;
    out = modelFiducials; %#ok<NASGU>
    outForSave = modelFiducials; %#ok<NASGU>
    save(modelFiducialsFile, 'out', 'outForSave', '-v7.3');
    fprintf('Reused generated synthetic model fiducials:\n  %s\n', ...
        modelFiducialsFile);
end

disp(table(modelFiducials.labels(:), modelFiducials.coordinatesMm(:, 1), ...
    modelFiducials.coordinatesMm(:, 2), modelFiducials.coordinatesMm(:, 3), ...
    'VariableNames', {'Label', 'Xmm', 'Ymm', 'Zmm'}));

%% 08 - Select A Brain Target Voxel
% Objective: choose the brain location that tES optimization should attempt to
% stimulate. Real studies may pick this from MRI anatomy, an atlas, functional
% data, or a planned recording chamber trajectory.
%
% For a real experiment this is where the user chooses the target brain voxel.
% The synthetic run uses a stored toy target unless interactive selections are
% enabled.

targetVoxelFile = fullfile(cfg.outputDir, ...
    sprintf('%s_demoTargetVoxel.mat', cfg.subjectId));

if cfg.interactiveSelections
    targetPick = acsLabelVolumeOrientation(syntheticOut.t1File, ...
        'orientationCode', 'ras', ...
        'volumeLabel', 'Synthetic demo T1', ...
        'initialVoxel', syntheticOut.demoTargets.targetVoxel, ...
        'voxelSelectionMode', 'single', ...
        'waitForDone', true, ...
        'doneButtonLabel', 'Accept target', ...
        'showFigures', true, ...
        'saveFigures', cfg.saveFigures, ...
        'outputDir', fullfile(cfg.outputDir, 'qc'), ...
        'outputName', sprintf('%s_targetVoxelPicker', cfg.subjectId), ...
        'closeFigure', false, ...
        'verbose', true);
    targetVoxel = double(targetPick.selectedVoxels(1, :));
else
    targetVoxel = double(syntheticOut.demoTargets.targetVoxel);
    targetPick = struct('selectedVoxels', targetVoxel, ...
        'source', struct('file', syntheticOut.t1File), ...
        'note', 'Generated synthetic target reused without opening picker.');
end

targetSelection = struct();
targetSelection.createdOn = char(datetime('now'));
targetSelection.type = 'syntheticTargetSelection';
targetSelection.targetVoxel = targetVoxel;
targetSelection.targetWorldMm = targetVoxel .* syntheticOut.geometry.voxelSizeMm;
targetSelection.source = stripGraphicsHandles(targetPick);
save(targetVoxelFile, 'targetSelection', '-v7.3');

fprintf('Demo target voxel: [%g %g %g]\n', targetVoxel);

%% 09 - Build The Initial tES Candidate Layout
% Objective: place an initial set of legal candidate tES contacts on scalp that
% survived the crop, ear/face exclusions, strap constraints, and implant
% keepouts. These candidates are possible model/electrode locations, not
% necessarily the final active montage.
%
% These are candidate tES contacts, not the final active montage. The layout
% uses the ear, strap, and headpost keepouts defined above.

customLocationsFile = fullfile(roastFolder, [t1Stem '_customLocations']);
targetOptions = baseCapTargetOptions(cfg);
targetOptions = addHeadpostKeepout(targetOptions, headpostExclusion);

candidateLayout = acsMakeRoastCapMakerLayout(syntheticOut, ...
    'surfaceSource', 'capMaker', ...
    'subjectId', cfg.subjectId, ...
    'skinCacheFile', capSkin.cacheFile, ...
    'nElectrodes', cfg.initialTesCandidates, ...
    'outputFile', customLocationsFile, ...
    'targetOptions', targetOptions, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', earExclusionFile, ...
    'strapExclusionMode', 'auto', ...
    'forceLayout', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 10 - Grow tES Candidates With Dummy Or ROAST Leadfields
% Objective: estimate which scalp locations are most useful for focally
% stimulating the selected target. Each iteration solves/approximates lead
% fields, chooses a sparse active montage, and proposes new candidate contacts
% while balancing predicted quality and exploration.
%
% The default dummy mode lets reviewers exercise sparse optimization and UCB
% candidate growth quickly. Set cfg.leadFieldMode='roast' to run real
% ROAST/GetDP leadfield solves on the tiny synthetic model and time the path.

growthHistory = repmat(struct('layout', [], 'leadField', [], ...
    'sparse', [], 'proposal', []), cfg.nGrowthSteps + 1, 1);
currentLayout = candidateLayout;
currentLeadField = [];
currentSparse = [];

fprintf('\nSynthetic tES growth walkthrough\n');
fprintf('  iterations: %d growth step(s) plus one final sparse solve\n', ...
    cfg.nGrowthSteps);
fprintf('  lead-field mode: %s\n', cfg.leadFieldMode);
if useRealLeadFields(cfg)
    fprintf('  ROAST/GetDP solves can still take minutes, even for this toy head.\n');
else
    fprintf('  lead fields: dummy/synthetic, not a physical ROAST solve\n');
end
fprintf('  sparse search mode: %s\n', cfg.sparseSearchMode);

for g = 1:(cfg.nGrowthSteps + 1)
    currentCount = numel(currentLayout.names);
    leadFieldTag = leadFieldTagForMode(cfg, currentCount);
    if g <= cfg.nGrowthSteps
        fprintf('\nGrowth iteration %d/%d: %d candidate contacts\n', ...
            g, cfg.nGrowthSteps, currentCount);
    else
        fprintf('\nFinal sparse solve on %d candidate contacts\n', currentCount);
    end
    leadTimer = tic;
    if useRealLeadFields(cfg)
        fprintf('  Step 1: running ROAST leadfield solve (%s)...\n', leadFieldTag);
        currentLeadField = acsGenerateRoastLeadField(currentLayout, ...
            'simulationTag', leadFieldTag, ...
            'resampling', cfg.realLeadFieldResampling, ...
            'segMaskFile', syntheticOut.maskFile, ...
            'electrodeModel', cfg.realLeadFieldElectrodeModel, ...
            'roastOptions', realLeadFieldRoastOptions(cfg), ...
            'showFigures', cfg.realLeadFieldShowFigures, ...
            'execute', true, ...
            'saveReport', true);
    else
        fprintf('  Step 1: writing dummy lead field (%s)...\n', leadFieldTag);
        currentLeadField = acsGenerateDummyRoastLeadField(currentLayout, ...
            'simulationTag', leadFieldTag, ...
            'meshSpacingMm', cfg.dummyLeadFieldMeshSpacingMm, ...
            'force', cfg.force, ...
            'saveReport', true, ...
            'verbose', true);
    end
    fprintf('  Step 1 complete in %.1f s.\n', toc(leadTimer));

    fprintf('  Step 2: optimizing sparse %d-contact montage...\n', ...
        cfg.activeTesChannels);
    currentSparse = acsOptimizeSparseRoastLeadField( ...
        currentLayout.t1File, currentLeadField.simulationTag, targetVoxel, ...
        'orientation', cfg.targetOrientation, ...
        'targetRadiusMm', cfg.targetRadiusMm, ...
        'activeElectrodeCount', cfg.activeTesChannels, ...
        'searchMode', cfg.sparseSearchMode, ...
        'targetingTag', sprintf('%s_demoTes%d', ...
            cfg.subjectId, cfg.activeTesChannels), ...
        'maxFilenameBaseChars', 72, ...
        'returnMeshField', false, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'saveReport', true, ...
        'verbose', true);

    growthHistory(g).layout = currentLayout;
    growthHistory(g).leadField = currentLeadField;
    growthHistory(g).sparse = currentSparse;

    if g > cfg.nGrowthSteps
        break;
    end

    fprintf('  Step 3: proposing %d new candidate contact(s) with UCB...\n', ...
        cfg.nNewCandidatesPerStep);
    proposal = acsProposeRoastCandidateGrowth(currentLayout, currentSparse, ...
        'nNew', cfg.nNewCandidatesPerStep, ...
        'poolSize', 48, ...
        'kernelSigmaMm', 'auto', ...
        'acquisitionMode', 'ucb', ...
        'ucbBeta', 1, ...
        'electrodeFootprintDiameterMm', cfg.demoElectrodeFootprintDiameterMm, ...
        'electrodeClearanceMm', cfg.demoElectrodeClearanceMm, ...
        'minDistanceFromExistingMm', cfg.demoMinDistanceMm, ...
        'minDistanceAmongNewMm', cfg.demoMinDistanceMm, ...
        'targetOptions', targetOptions, ...
        'earExclusionMode', 'never', ...
        'earExclusionFile', earExclusionFile, ...
        'strapExclusionMode', 'auto', ...
        'makeLayout', true, ...
        'outputFile', customLocationsFile, ...
        'forceLayout', true, ...
        'proposalTag', sprintf('%s_demoGrow%02d', cfg.subjectId, g), ...
        'maxFilenameBaseChars', 72, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'saveReport', true, ...
        'verbose', true);

    growthHistory(g).proposal = proposal;
    currentLayout = proposal.expandedLayout;
    fprintf('  Iteration %d complete: %d -> %d candidates.\n', ...
        g, currentCount, numel(currentLayout.names));
end

finalCandidateLayout = currentLayout;
finalLeadField = currentLeadField;
finalSparse = currentSparse;

fprintf('Final synthetic candidate layout: %d contacts\n', ...
    numel(finalCandidateLayout.names));
fprintf('Selected tES contacts: %s\n', ...
    strjoin(cellstr(finalSparse.selectedNames(:))', ', '));

%% 10.5 - Visualize The Real Sparse Electric Field
% Objective: show the predicted electric field for the optimized montage when
% real ROAST/GetDP lead fields were computed. Dummy mode skips this because it
% is not a physical field model.
%
% This section is intentionally skipped in dummy mode. When cfg.leadFieldMode
% is 'roast', it reconstructs the optimized field from the solved leadfield
% and displays target-centered surface/slice QC.

if useRealLeadFields(cfg)
    finalFieldQc = acsVisualizeSparseRoastLeadField(finalSparse, ...
        'colorLimitPercentile', 99.95, ...
        'showElectrodeLabels', false, ...
        'showFigures', cfg.showFigures, ...
        'saveFigures', cfg.saveFigures, ...
        'closeFigure', false);
else
    finalFieldQc = [];
    fprintf(['Skipping real electric-field visualization because ', ...
        'cfg.leadFieldMode=''%s''.\n'], cfg.leadFieldMode);
end

%% 11 - Interleave EEG Electrodes Around The Optimized tES Montage
% Objective: add EEG electrodes to the remaining legal scalp. EEG placement is
% optimized for coverage of available scalp while avoiding tES holders and all
% manufacturing exclusions.
%
% The selected tES sites are renamed customTES#, and new EEG sites are added
% where they cover the remaining legal scalp while avoiding tES holders and
% manufacturing exclusions.

combinedCustomLocationsFile = fullfile(roastFolder, ...
    [t1Stem '_tesEeg_customLocations']);

eegTargetOptions = baseCapTargetOptions(cfg);
eegTargetOptions = addHeadpostKeepout(eegTargetOptions, headpostExclusion);
eegTargetOptions.voronoiIterations = 6;
eegTargetOptions.voronoiSpacingIterations = 3;

combinedLayout = acsAssembleTesEegCapMakerLayout( ...
    finalCandidateLayout, finalSparse, ...
    'nTes', cfg.activeTesChannels, ...
    'nEeg', cfg.nEegChannels, ...
    'skinCacheFile', capSkin.cacheFile, ...
    'eegTargetOptions', eegTargetOptions, ...
    'eegExclusionRadiusMm', cfg.demoEegTesClearanceMm, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', earExclusionFile, ...
    'strapExclusionMode', 'auto', ...
    'outputFile', combinedCustomLocationsFile, ...
    'forceLayout', true, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

disp(table(combinedLayout.names(:), combinedLayout.siteRoles(:), ...
    combinedLayout.layoutCoordinatesMm(:, 1), ...
    combinedLayout.layoutCoordinatesMm(:, 2), ...
    combinedLayout.layoutCoordinatesMm(:, 3), ...
    'VariableNames', {'Name', 'Role', 'Xmm', 'Ymm', 'Zmm'}));

%% 11.5 - Review The tES Stimulation Parameters
% Objective: display the final tES current recipe in a lab-facing table. This
% utility can also be run later from a clean workspace with no arguments, or
% with a saved layout/manufacturing report MAT file or tag.
%
% In dummy mode this is just a plumbing check. In ROAST mode, it can replay the
% saved electric-field figure when the solved lead-field products are present.

stimulationFieldReplayMode = 'never';
if useRealLeadFields(cfg)
    stimulationFieldReplayMode = 'auto';
end

stimulationReview = acsShowTesStimulationParameters(combinedLayout, ...
    'sparseResult', finalSparse, ...
    'showField', stimulationFieldReplayMode, ...
    'showEegTopography', 'auto', ...
    'saveFigures', cfg.saveFigures, ...
    'verbose', true);

%% 12 - Export Final Dual-Material Cap STLs
% Objective: turn the layout into printable geometry. The TPE/rubber part
% contains flexible rails and electrode holders; the PLA part provides support
% and underfill needed by the print process. Inspect these files before any
% real use.
%
% This creates separate TPE and PLA STL files plus a manufacturing QC figure.
% The synthetic STL is for software inspection only.

manufacturingDir = fullfile(cfg.outputDir, 'manufacturing', ...
    sprintf('%s_syntheticDualMaterialCap', cfg.subjectId));

manufacturing = acsBuildCapMakerManufacturingStl(combinedLayout, ...
    'skinCacheFile', capSkin.cacheFile, ...
    'outputDir', manufacturingDir, ...
    'manufacturingTag', sprintf('%s_syntheticDualMaterialCap', cfg.subjectId), ...
    'force', cfg.force, ...
    'electrodeNames', combinedLayout.names, ...
    'earExclusionMode', 'never', ...
    'earExclusionFile', earExclusionFile, ...
    'implantExclusionFile', {headpostExclusionFile}, ...
    'holderPlacementSurfaceMode', 'full', ...
    'holderSnapErrorDistanceMm', 5, ...
    'manufacturingSurfaceMaxFaces', cfg.finalManufacturingSurfaceMaxFaces, ...
    'railSurfaceMaxFaces', cfg.finalRailSurfaceMaxFaces, ...
    'railEdgeMarginMm', cfg.finalRailEdgeMarginMm, ...
    'voxelSizeMm', 1.0, ...
    'minFinalTpeComponentVoxels', 5, ...
    'minFinalPlaComponentVoxels', 5, ...
    'showQcLabels', false, ...
    'showFigures', cfg.showFigures, ...
    'saveFigures', cfg.saveFigures, ...
    'saveMeshMat', true, ...
    'returnMeshes', true, ...
    'verbose', true);

fprintf('\nSynthetic walkthrough complete.\n');
fprintf('  output folder: %s\n', cfg.outputDir);
if isfield(manufacturing, 'stlFiles')
    disp(manufacturing.stlFiles)
elseif isfield(manufacturing, 'tpeStlFile')
    fprintf('  TPE STL: %s\n', manufacturing.tpeStlFile);
    fprintf('  PLA STL: %s\n', manufacturing.plaStlFile);
end

clear restoreFigureWindowStyle;

%% 13 - Verify The Synthetic Walkthrough Products
% Objective: give reviewers a quick, file-level confirmation that the tutorial
% reached the expected output classes. This does not prove scientific validity;
% it catches missing products and broken plumbing.
%
% This lightweight check does not recompute anything. It verifies that the
% expected files from the synthetic tutorial exist and that key MAT products
% can be inspected.

walkthroughVerification = nhpulseVerifySyntheticWalkthrough(cfg.outputDir, ...
    'subjectId', cfg.subjectId, ...
    'requireFinalCap', true, ...
    'requireRealLeadField', useRealLeadFields(cfg), ...
    'verbose', true);

function opts = baseCapTargetOptions(cfg)
    if nargin < 1
        cfg = struct();
    end
    opts = struct();
    opts.placementMode = 'surfaceVoronoi';
    opts.edgeMarginMM = getFieldOrDefault(cfg, 'layoutEdgeMarginMm', 4);
    opts.bedMarginMM = getFieldOrDefault(cfg, 'layoutBedMarginMm', 2);
    opts.bottomFaceBandMM = 1.5;
    opts.normalUpDotMin = getFieldOrDefault(cfg, 'layoutNormalUpDotMin', 0.2);
    opts.normalMode = 'smooth';
    opts.normalSmoothRadiusMM = 6;
    opts.visibleFromAbove = false;
    opts.preferSymmetry = false;
    opts.midlineMarginMM = 0;
    opts.voronoiIterations = 5;
    opts.voronoiToleranceMM = 0.25;
    opts.voronoiSnapMode = 'spacingAware';
    opts.voronoiSpacingWeight = 4;
    opts.voronoiMinSpacingFraction = 0.65;
    opts.voronoiSpacingIterations = 2;
    opts.voronoiMaxCandidatesPerCell = 60;
    opts.vizSurfaceGeodesic = false;
    opts.vizSurfaceVoronoi = false;
end

function opts = addHeadpostKeepout(opts, headpostExclusion)
    if isempty(headpostExclusion) || ~isstruct(headpostExclusion)
        return;
    end
    center = [];
    if isfield(headpostExclusion, 'footprintInfo') && ...
            isstruct(headpostExclusion.footprintInfo) && ...
            isfield(headpostExclusion.footprintInfo, 'centerMm')
        center = double(headpostExclusion.footprintInfo.centerMm);
    elseif isfield(headpostExclusion, 'keepoutBoundaryMm') && ...
            ~isempty(headpostExclusion.keepoutBoundaryMm)
        center = mean(double(headpostExclusion.keepoutBoundaryMm), 1);
    end
    if isempty(center)
        return;
    end
    center = center(:)';
    radius = getFieldOrDefault(headpostExclusion, 'keepoutRadiusMm', []);
    if isempty(radius) || ~isscalar(radius) || ~isfinite(radius)
        radius = 16;
    end
    if ~isfield(opts, 'exclusionCenters') || isempty(opts.exclusionCenters)
        opts.exclusionCenters = zeros(0, 3);
        opts.exclusionRadiusMM = zeros(0, 1);
    end
    opts.exclusionCenters = [double(opts.exclusionCenters); center(1:3)];
    opts.exclusionRadiusMM = [double(opts.exclusionRadiusMM(:)); double(radius)];
end

function value = getFieldOrDefault(S, fieldName, defaultValue)
    if isstruct(S) && isfield(S, fieldName) && ~isempty(S.(fieldName))
        value = S.(fieldName);
    else
        value = defaultValue;
    end
end

function out = chooseMode(flag, trueValue, falseValue)
    if flag
        out = trueValue;
    else
        out = falseValue;
    end
end

function tf = useRealLeadFields(cfg)
    mode = lower(strtrim(char(getFieldOrDefault(cfg, 'leadFieldMode', 'dummy'))));
    tf = any(strcmp(mode, {'roast', 'real', 'getdp'}));
end

function tag = leadFieldTagForMode(cfg, currentCount)
    if useRealLeadFields(cfg)
        modelTag = safeTagText(getFieldOrDefault( ...
            cfg, 'realLeadFieldElectrodeModel', 'auto'));
        suffix = safeTagText(getFieldOrDefault( ...
            cfg, 'realLeadFieldTagSuffix', ''));
        tag = sprintf('%s_roastLf%02d_%s', ...
            cfg.subjectId, currentCount, modelTag);
        if ~isempty(suffix)
            tag = sprintf('%s_%s', tag, suffix);
        end
    else
        tag = sprintf('%s_dummyLf%02d', cfg.subjectId, currentCount);
    end
end

function args = realLeadFieldRoastOptions(cfg)
    args = {};
    meshOptions = getFieldOrDefault(cfg, 'realLeadFieldMeshOptions', []);
    if ~isempty(meshOptions)
        args = [args, {'meshOptions', meshOptions}];
    end
end

function txt = safeTagText(value)
    txt = lower(regexprep(char(value), '[^A-Za-z0-9]+', ''));
    maxChars = 24;
    if numel(txt) > maxChars
        txt = txt(1:maxChars);
    end
end

function S = stripGraphicsHandles(S)
    if isstruct(S)
        if isfield(S, 'figure')
            S = rmfield(S, 'figure');
        end
        names = fieldnames(S);
        for i = 1:numel(names)
            value = S.(names{i});
            if isstruct(value)
                S.(names{i}) = stripGraphicsHandles(value);
            end
        end
    end
end

function cleaner = setTemporaryFigureWindowStyle(style)
    oldStyle = get(groot, 'defaultFigureWindowStyle');
    set(groot, 'defaultFigureWindowStyle', style);
    cleaner = onCleanup(@() set(groot, 'defaultFigureWindowStyle', oldStyle));
end
