function info = nhpulseDependencyInfo(name)
% NHPULSEDEPENDENCYINFO Return install/config help for common dependencies.
%
% info = nhpulseDependencyInfo('SPM') returns a struct with the official
% project URL, install URL, local config field, and short setup guidance.

    key = lower(regexprep(char(name), '[^a-zA-Z0-9]', ''));

    switch key
        case {'matlab'}
            info = item('MATLAB', ...
                'https://www.mathworks.com/products/matlab.html', ...
                'https://www.mathworks.com/help/install/', ...
                '', ...
                'MATLAB is the required runtime for NHPulse.');
        case {'spm', 'spm12'}
            info = item('SPM', ...
                'https://www.fil.ion.ucl.ac.uk/spm/software/', ...
                'https://www.fil.ion.ucl.ac.uk/spm/docs/installation/', ...
                'spmPath', ...
                ['Install SPM, then add its folder to MATLAB with ', ...
                 'setNHPulsePath or nhpulseConfigureLocalPaths. On macOS, ', ...
                 'run nhpulseClearMacQuarantine(''spm'') if MEX files are blocked.']);
        case {'imageprocessingtoolbox', 'imageprocessing'}
            info = item('Image Processing Toolbox', ...
                'https://www.mathworks.com/products/image-processing.html', ...
                'https://www.mathworks.com/products/image-processing.html', ...
                '', ...
                'Install through MathWorks Add-On Explorer or your MATLAB license portal.');
        case {'statisticsandmachinelearningtoolbox', 'statistics'}
            info = item('Statistics and Machine Learning Toolbox', ...
                'https://www.mathworks.com/products/statistics.html', ...
                'https://www.mathworks.com/products/statistics.html', ...
                '', ...
                'Install through MathWorks Add-On Explorer or your MATLAB license portal.');
        case {'cvx'}
            info = item('CVX', ...
                'https://cvxr.com/cvx/', ...
                'https://cvxr.com/cvx/download/', ...
                'cvxPath', ...
                ['Install CVX, run cvx_setup if needed, then add the CVX ', ...
                 'folder using nhpulseConfigureLocalPaths. On macOS, run ', ...
                 'nhpulseClearMacQuarantine(''cvx'') if MEX files are blocked.']);
        case {'iso2mesh', 'iso2meshtetgen', 'tetgen'}
            info = item('iso2mesh/TetGen', ...
                'https://github.com/fangq/iso2mesh', ...
                'https://sourceforge.net/projects/iso2mesh/files/iso2mesh/', ...
                'iso2meshPath', ...
                ['Install iso2mesh/TetGen for full meshing workflows, then ', ...
                 'add the iso2mesh folder using nhpulseConfigureLocalPaths.']);
        case {'getdp'}
            info = item('GetDP', ...
                'https://getdp.info/', ...
                'https://getdp.info/', ...
                'getdpExecutable', ...
                ['Install GetDP for finite-element solves, then set the ', ...
                 'getdpExecutable field in local.paths.json.']);
        case {'gmsh'}
            info = item('Gmsh', ...
                'https://gmsh.info/', ...
                'https://gmsh.info/#Download', ...
                'gmshExecutable', ...
                ['Install Gmsh for ROAST mesh visualization/support, then set ', ...
                 'the gmshExecutable field in local.paths.json.']);
        case {'nifti', 'niftiutilities'}
            info = item('NIfTI utilities', ...
                'https://www.mathworks.com/help/images/ref/niftiread.html', ...
                'https://www.mathworks.com/help/images/ref/niftiread.html', ...
                'niftiPath', ...
                ['NHPulse includes SPM-backed load_untouch_nii/save_untouch_nii ', ...
                 'wrappers for ROAST. niftiPath is only needed if you want ', ...
                 'to provide a separate legacy NIfTI toolbox.']);
        case {'roastnifticompatibility'}
            info = item('ROAST NIfTI compatibility', ...
                'https://www.fil.ion.ucl.ac.uk/spm/software/', ...
                'https://www.fil.ion.ucl.ac.uk/spm/docs/installation/', ...
                'spmPath', ...
                ['Run setNHPulsePath from the repository root so NHPulse can ', ...
                 'find its load_untouch_nii/save_untouch_nii wrappers, and ', ...
                 'install/configure SPM for the underlying NIfTI I/O.']);
        case {'inpolyhedron'}
            info = item('inpolyhedron', ...
                'https://www.mathworks.com/matlabcentral/fileexchange/37856-inpolyhedron-are-points-inside-a-triangulated-volume', ...
                'https://www.mathworks.com/matlabcentral/fileexchange/37856-inpolyhedron-are-points-inside-a-triangulated-volume', ...
                'inpolyhedronPath', ...
                'NHPulse includes acsUtilities/inpolyhedron.m; no separate install is normally needed.');
        otherwise
            info = item(char(name), '', '', '', ...
                'No dependency metadata is available for this item yet.');
    end
end

function info = item(name, projectUrl, installUrl, configField, setupHint)
    info = struct();
    info.name = name;
    info.projectUrl = projectUrl;
    info.installUrl = installUrl;
    info.configField = configField;
    info.setupHint = setupHint;
end
