function registry = nhpulseArtifactTypes(varargin)
% NHPULSEARTIFACTTYPES Return the extensible NHPulse artifact hierarchy.
%
% registry = nhpulseArtifactTypes() returns built-in artifact definitions.
% The hierarchy describes stages and valid parent relationships without
% changing where pipeline files are written.
%
% registry = nhpulseArtifactTypes('additionalTypes', definitions) appends or
% replaces definitions by type name. Custom definitions may omit fields; the
% defaults documented by an entry in the returned registry are supplied.

    p = inputParser;
    addParameter(p, 'additionalTypes', struct([]), @isstruct);
    parse(p, varargin{:});

    registry = builtInTypes();
    additional = p.Results.additionalTypes;
    for i = 1:numel(additional)
        definition = normalizeDefinition(additional(i));
        idx = find(strcmp({registry.type}, definition.type), 1);
        if isempty(idx)
            registry(end + 1, 1) = definition; %#ok<AGROW>
        else
            registry(idx) = definition;
        end
    end
end

function registry = builtInTypes()
    registry = repmat(emptyDefinition(), 0, 1);
    registry(end + 1) = define('nhpulse.anatomy', 'Anatomical image', ...
        'anatomy', 10, 'root', {}, {'.nii', '.gz'}, 100, ...
        {'(^|[/\\])[^/\\]*(_t1|t1_|anatom)[^/\\]*\.nii(\.gz)?$'});
    registry(end + 1) = define('nhpulse.segmentation', 'Tissue segmentation', ...
        'segmentation', 20, 'listed', {'nhpulse.anatomy'}, ...
        {'.nii', '.gz', '.mat'}, 120, ...
        {'_masks[^/\\]*\.nii(\.gz)?$', 'segmentation[^/\\]*\.(nii|mat)$', ...
         '_skinclean\.nii(\.gz)?$'});
    registry(end + 1) = define('nhpulse.registration', 'Spatial registration', ...
        'registration', 30, 'listed', ...
        {'nhpulse.anatomy', 'nhpulse.scalpModel'}, {'.mat', '.json'}, 130, ...
        {'registration[^/\\]*\.mat$', 'phonetomri[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.fiducials', 'Spatial fiducials', ...
        'registration', 32, 'listed', ...
        {'nhpulse.anatomy', 'nhpulse.scalpModel', 'nhpulse.registration'}, ...
        {'.mat', '.json', '.txt'}, 135, ...
        {'fiducial[^/\\]*\.(mat|json|txt)$'});
    registry(end + 1) = define('nhpulse.scalpModel', 'Scalp surface model', ...
        'scalp', 35, 'listed', ...
        {'nhpulse.anatomy', 'nhpulse.segmentation', 'nhpulse.registration', ...
         'nhpulse.scalpModel', 'nhpulse.cropPlane'}, ...
        {'.mat', '.stl', '.ply'}, 125, ...
        {'skinmesh[^/\\]*\.mat$', 'warpedfullheadskinmesh\.mat$', ...
         'printerbedskinmesh\.mat$', 'scalp[^/\\]*\.(mat|stl|ply)$'});
    registry(end + 1) = define('nhpulse.cropPlane', 'Manufacturing crop plane', ...
        'subject geometry', 40, 'listed', {'nhpulse.scalpModel'}, {'.mat'}, 150, ...
        {'cropplane\.mat$'});
    registry(end + 1) = define('nhpulse.implantPlacement', 'Implant placement', ...
        'subject geometry', 42, 'listed', ...
        {'nhpulse.scalpModel', 'nhpulse.registration', 'nhpulse.anatomy', ...
         'nhpulse.segmentation', 'nhpulse.implantTrace', ...
         'nhpulse.exclusion'}, ...
        {'.mat', '.stl'}, 145, ...
        {'(headpost|chamber)[^/\\]*(placement|mesh)[^/\\]*\.(mat|stl)$'});
    registry(end + 1) = define('nhpulse.implantTrace', 'Observed implant trace', ...
        'subject geometry', 41, 'listed', ...
        {'nhpulse.registration', 'nhpulse.scalpModel', 'nhpulse.fiducials'}, ...
        {'.mat', '.json', '.txt', '.ply'}, 130, ...
        {'(headpost|implant)[^/\\]*(trace|object)[^/\\]*\.(mat|json|txt|ply)$'});
    registry(end + 1) = define('nhpulse.exclusion', 'Manufacturing exclusion', ...
        'subject geometry', 45, 'listed', ...
        {'nhpulse.scalpModel', 'nhpulse.cropPlane', 'nhpulse.implantPlacement'}, ...
        {'.mat'}, 145, {'(exclusion|keepout)[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.target', 'Stimulation target', ...
        'targeting', 48, 'listed', ...
        {'nhpulse.anatomy', 'nhpulse.segmentation'}, {'.mat', '.nii', '.gz'}, 110, ...
        {'target[^/\\]*\.(mat|nii|nii\.gz)$'});
    registry(end + 1) = define('nhpulse.candidateLayout', 'Candidate electrode layout', ...
        'layout', 50, 'listed', ...
        {'nhpulse.scalpModel', 'nhpulse.segmentation', 'nhpulse.cropPlane', ...
         'nhpulse.exclusion', 'nhpulse.implantPlacement', 'nhpulse.target', ...
         'nhpulse.candidateLayout', 'nhpulse.optimizedMontage'}, ...
        {'.mat', '.txt', '.csv'}, 115, ...
        {'customlocations[^/\\]*\.(mat|txt|csv)$', ...
         '(candidate|layoutgrowth)[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.leadField', 'Electrical lead field', ...
        'modeling', 60, 'listed', ...
        {'nhpulse.segmentation', 'nhpulse.candidateLayout', ...
         'nhpulse.implantPlacement'}, {'.mat'}, 140, ...
        {'(leadfield|roastresult)[^/\\]*\.mat$', '_lf[0-9]+[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.optimizedMontage', 'Optimized tES montage', ...
        'optimization', 70, 'listed', ...
        {'nhpulse.leadField', 'nhpulse.target', 'nhpulse.candidateLayout'}, ...
        {'.mat', '.json', '.csv'}, 135, ...
        {'(sparse|optimized)[^/\\]*(montage|solution|tes)[^/\\]*\.(mat|json|csv)$'});
    registry(end + 1) = define('nhpulse.combinedLayout', 'Combined tES/EEG layout', ...
        'layout', 75, 'listed', ...
        {'nhpulse.optimizedMontage', 'nhpulse.candidateLayout', ...
         'nhpulse.exclusion', 'nhpulse.scalpModel'}, {'.mat', '.txt', '.csv'}, 155, ...
        {'teseeg[^/\\]*customlocations[^/\\]*\.(mat|txt|csv)$', ...
         'combinedlayout[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.eegPrediction', 'Predicted EEG topography', ...
        'prediction', 80, 'listed', ...
        {'nhpulse.leadField', 'nhpulse.optimizedMontage', ...
         'nhpulse.combinedLayout'}, {'.mat', '.json', '.csv'}, 150, ...
        {'(eegvoltageprediction|eegtopography|teseegtransfer)[^/\\]*\.(mat|json|csv)$'});
    registry(end + 1) = define('nhpulse.retentionPlan', ...
        'Cap retention plan', 'manufacturing', 81, 'listed', ...
        {'nhpulse.combinedLayout', 'nhpulse.scalpModel', ...
         'nhpulse.exclusion'}, {'.mat', '.json'}, 155, ...
        {'(velcro|retention)[^/\\]*(anchor|plan)[^/\\]*\.(mat|json)$'});
    registry(end + 1) = define('nhpulse.manufacturingGeometry', ...
        'Cap manufacturing geometry', 'manufacturing', 82, 'listed', ...
        {'nhpulse.combinedLayout', 'nhpulse.scalpModel', 'nhpulse.cropPlane', ...
         'nhpulse.exclusion', 'nhpulse.implantPlacement', ...
         'nhpulse.retentionPlan'}, {'.mat'}, 150, ...
        {'manufacturing[^/\\]*report\.mat$', 'manufacturinggeometry[^/\\]*\.mat$'});
    registry(end + 1) = define('nhpulse.fitCheck', 'PLA fit-check cap', ...
        'manufacturing', 85, 'listed', ...
        {'nhpulse.manufacturingGeometry', 'nhpulse.scalpModel', ...
         'nhpulse.exclusion', 'nhpulse.candidateLayout', ...
         'nhpulse.combinedLayout'}, {'.mat', '.stl'}, 160, ...
        {'fitcheck[^/\\]*\.(mat|stl)$', 'sparsepla[^/\\]*\.(mat|stl)$'});
    registry(end + 1) = define('nhpulse.manufacturingStl', 'Printable cap STL', ...
        'manufacturing', 90, 'listed', ...
        {'nhpulse.manufacturingGeometry', 'nhpulse.combinedLayout'}, {'.stl'}, 170, ...
        {'_(pla|tpe)\.stl$', 'manufacturing[^/\\]*\.stl$'});
    registry(end + 1) = define('nhpulse.stimulationProtocol', ...
        'Experimental stimulation protocol', 'experiment', 95, 'listed', ...
        {'nhpulse.optimizedMontage', 'nhpulse.eegPrediction', ...
         'nhpulse.combinedLayout'}, {'.mat', '.json', '.csv'}, 165, ...
        {'(protocol|stimulationparameters|tescontrast)[^/\\]*\.(mat|json|csv)$'});
    registry(end + 1) = define('nhpulse.qcFigure', 'Quality-control figure', ...
        'quality control', 100, 'any', {}, ...
        {'.png', '.jpg', '.jpeg', '.pdf', '.fig'}, 20, ...
        {'(^|[/\\])qc[/\\].*\.(png|jpg|jpeg|pdf|fig)$', '_qc\.(png|fig)$'});
    registry = registry(:);
end

function value = define(type, label, stage, order, policy, parents, ...
        extensions, priority, patterns)
    value = emptyDefinition();
    value.type = type;
    value.label = label;
    value.stage = stage;
    value.stageOrder = order;
    value.parentPolicy = policy;
    value.allowedParentTypes = parents(:).';
    value.extensions = extensions(:).';
    value.legacyPriority = priority;
    value.legacyPatterns = patterns(:).';
    value.description = label;
end

function value = normalizeDefinition(input)
    value = emptyDefinition();
    names = fieldnames(input);
    for i = 1:numel(names)
        if ~isfield(value, names{i})
            error('nhpulseArtifactTypes:UnknownField', ...
                'Unknown artifact definition field "%s".', names{i});
        end
        value.(names{i}) = input.(names{i});
    end
    if isempty(value.type)
        error('nhpulseArtifactTypes:MissingType', ...
            'Each artifact definition requires a nonempty type.');
    end
    value.type = char(value.type);
    value.label = char(value.label);
    value.stage = char(value.stage);
    value.parentPolicy = lower(char(value.parentPolicy));
    if ~any(strcmp(value.parentPolicy, {'root', 'listed', 'any'}))
        error('nhpulseArtifactTypes:BadParentPolicy', ...
            'parentPolicy must be root, listed, or any.');
    end
    value.allowedParentTypes = cellstr(value.allowedParentTypes);
    value.extensions = cellfun(@lower, cellstr(value.extensions), ...
        'UniformOutput', false);
    value.legacyPatterns = cellstr(value.legacyPatterns);
end

function value = emptyDefinition()
    value = struct('type', '', 'label', '', 'stage', 'extension', ...
        'stageOrder', 999, 'description', '', 'parentPolicy', 'any', ...
        'allowedParentTypes', {{}}, 'extensions', {{}}, ...
        'legacyPriority', 0, 'legacyPatterns', {{}});
end
