function output = nhpulseServiceBuildCombinedLayout(context, inputs, config)
% NHPULSESERVICEBUILDCOMBINEDLAYOUT Build/register final tES+EEG layout.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.candidateLayout');
    montage = resolveRequired(context, inputs, 'montage', ...
        'nhpulse.optimizedMontage');
    scalp = resolveRequired(context, inputs, 'scalp', 'nhpulse.scalpModel');
    exclusion = resolveOptional(context, inputs, 'anatomicalExclusion', ...
        'nhpulse.exclusion');
    layoutValue = nhpulseServiceInternal('loadValue', layout);
    montageValue = nhpulseServiceInternal('loadValue', montage);
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'layout', ...
        'combinedTesEeg_customLocations'));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    earFile = '';
    if ~isempty(exclusion), earFile = exclusion.path; end
    result = acsAssembleTesEegCapMakerLayout(layoutValue, montageValue, args{:}, ...
        'nTes', nhpulseServiceInternal('field', config, 'nTes', 8), ...
        'nEeg', nhpulseServiceInternal('field', config, 'nEeg', 8), ...
        'skinCacheFile', scalp.path, ...
        'earExclusionMode', 'never', 'earExclusionFile', earFile, ...
        'outputFile', outputFile, ...
        'forceLayout', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    parentKeys = {montage.artifactKey, layout.artifactKey, scalp.artifactKey};
    parentRoles = {'optimizedMontage', 'candidateLayout', 'placementSurface'};
    if ~isempty(exclusion)
        parentKeys{end + 1} = exclusion.artifactKey;
        parentRoles{end + 1} = 'anatomicalExclusions';
    end
    metadata = struct('channelNames', {cellstr(result.names(:))}, ...
        'siteRoles', {cellstr(result.siteRoles(:))}, ...
        'coordinatesMm', double(result.layoutCoordinatesMm));
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'combined-layout');
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.combinedLayout', result.reportMat, ...
        'label', 'Final combined tES/EEG layout', ...
        'parentKeys', parentKeys, 'parentRoles', parentRoles, ...
        'metadata', metadata);
    output = nhpulseServiceInternal('result', 'buildCombinedLayout', context, ...
        result, struct('layout', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceBuildCombinedLayout:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end

function handle = resolveOptional(context, inputs, name, type)
    handle = [];
    if isstruct(inputs) && isfield(inputs, name) && ~isempty(inputs.(name))
        handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
            'expectedType', type);
    end
end
