function output = nhpulseServiceGrowCandidateLayout(context, inputs, config)
% NHPULSESERVICEGROWCANDIDATELAYOUT Propose/register an expanded layout.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.candidateLayout');
    montage = resolveRequired(context, inputs, 'montage', ...
        'nhpulse.optimizedMontage');
    exclusion = resolveOptional(context, inputs, 'anatomicalExclusion', ...
        'nhpulse.exclusion');
    layoutValue = nhpulseServiceInternal('loadValue', layout);
    montageValue = nhpulseServiceInternal('loadValue', montage);
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'layout', ...
        'grown_customLocations'));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    earFile = '';
    if ~isempty(exclusion), earFile = exclusion.path; end
    result = acsProposeRoastCandidateGrowth(layoutValue, montageValue, args{:}, ...
        'nNew', nhpulseServiceInternal('field', config, 'nNew', 2), ...
        'acquisitionMode', nhpulseServiceInternal('field', config, ...
        'acquisitionMode', 'ucb'), ...
        'ucbBeta', nhpulseServiceInternal('field', config, 'ucbBeta', 1), ...
        'earExclusionMode', 'never', 'earExclusionFile', earFile, ...
        'makeLayout', true, 'outputFile', outputFile, ...
        'forceLayout', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'saveReport', true, ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    expanded = result.expandedLayout;
    parentKeys = {layout.artifactKey, montage.artifactKey};
    parentRoles = {'growthStartingLayout', 'acquisitionMontage'};
    if ~isempty(exclusion)
        parentKeys{end + 1} = exclusion.artifactKey;
        parentRoles{end + 1} = 'anatomicalExclusions';
    end
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'grown-candidate-layout');
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.candidateLayout', expanded.reportMat, ...
        'label', 'Expanded tES candidate layout', ...
        'parentKeys', parentKeys, 'parentRoles', parentRoles);
    output = nhpulseServiceInternal('result', 'growCandidateLayout', context, ...
        result, struct('layout', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceGrowCandidateLayout:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end

function handle = resolveOptional(context, inputs, name, type)
    handle = [];
    if isstruct(inputs) && isfield(inputs, name) && ~isempty(inputs.(name))
        handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
            'expectedType', type);
    end
end
