function output = nhpulseServiceBuildScalp(context, inputs, config)
% NHPULSESERVICEBUILDSCALP Build/register a canonical full-head scalp.
%
% output = nhpulseServiceBuildScalp(context, inputs, config)
% inputs.segmentation is an explicit registered artifact reference.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    segmentation = nhpulseServiceInternal('resolve', context, ...
        requireInput(inputs, 'segmentation'), ...
        'expectedType', 'nhpulse.segmentation');
    key = nhpulseServiceInternal('field', config, 'artifactKey', 'full-head-scalp');
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'fullHeadScalp.mat'));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    result = acsBuildRoastScalpSkinCache(segmentation.path, args{:}, ...
        'outputFile', outputFile, ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'maxFaces', nhpulseServiceInternal('field', config, 'maxFaces', 35000), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', false), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    [artifact, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.scalpModel', result.cacheFile, ...
        'label', nhpulseServiceInternal('field', config, 'label', ...
        'Canonical full-head scalp'), ...
        'parentKeys', {segmentation.artifactKey}, ...
        'parentRoles', {'sourceSegmentation'});
    output = nhpulseServiceInternal('result', 'buildScalp', context, result, ...
        struct('scalp', handle, 'records', artifact), config);
end

function value = requireInput(inputs, name)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceBuildScalp:MissingInput', ...
            'inputs.%s is required.', name);
    end
    value = inputs.(name);
end
