function output = nhpulseServiceDefineFiducials(context, inputs, config)
% NHPULSESERVICEDEFINEFIDUCIALS Define/register model-space fiducials.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    scalp = resolveRequired(context, inputs, 'scalp', 'nhpulse.scalpModel');
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'modelFiducials.mat'));
    labels = nhpulseServiceInternal('field', config, 'fiducialLabels', ...
        {'Nas', 'Lpa', 'Rpa', 'Ini'});
    coordinates = nhpulseServiceInternal('field', config, 'coordinatesMm', []);
    if isempty(coordinates)
        args = nhpulseServiceInternal('options', ...
            nhpulseServiceInternal('field', config, 'engineOptions', struct()));
        result = acsSelectModelFiducials(scalp.path, args{:}, ...
            'fiducialLabels', labels, ...
            'meshStage', nhpulseServiceInternal('field', config, ...
            'meshStage', 'fullHead'), ...
            'outputFile', outputFile, ...
            'force', nhpulseServiceInternal('field', config, 'force', false), ...
            'editMode', nhpulseServiceInternal('field', config, ...
            'editMode', 'reuseOrEdit'), ...
            'showFigures', nhpulseServiceInternal('field', config, ...
            'showFigures', true), ...
            'saveFigures', nhpulseServiceInternal('field', config, ...
            'saveFigures', true), ...
            'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    else
        coordinates = double(coordinates);
        if size(coordinates, 2) ~= 3 || size(coordinates, 1) ~= numel(labels)
            error('nhpulseServiceDefineFiducials:BadCoordinates', ...
                'coordinatesMm must have one three-element row per label.');
        end
        result = struct('createdOn', char(datetime('now')), ...
            'labels', {cellstr(labels(:))}, 'coordinatesMm', coordinates, ...
            'source', struct('file', scalp.path), ...
            'selectionMode', 'providedCoordinates');
        folder = fileparts(outputFile);
        if exist(folder, 'dir') ~= 7, mkdir(folder); end
        out = result;
        outForSave = result;
        save(outputFile, 'out', 'outForSave', '-v7.3');
    end
    [record, handle] = nhpulseServiceInternal('record', context, ...
        nhpulseServiceInternal('field', config, 'artifactKey', ...
        'model-fiducials'), 'nhpulse.fiducials', outputFile, ...
        'label', 'Model-space fiducials', ...
        'parentKeys', {scalp.artifactKey}, ...
        'parentRoles', {'selectionSurface'});
    output = nhpulseServiceInternal('result', 'defineFiducials', context, ...
        result, struct('fiducials', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceDefineFiducials:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end
