function output = nhpulseServiceCropScalp(context, inputs, config)
% NHPULSESERVICECROPSCALP Crop/register scalp and printer-bed plane.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    scalp = nhpulseServiceInternal('resolve', context, ...
        requireInput(inputs, 'scalp'), 'expectedType', 'nhpulse.scalpModel');
    scalpKey = nhpulseServiceInternal('field', config, ...
        'scalpArtifactKey', 'printable-scalp');
    planeKey = nhpulseServiceInternal('field', config, ...
        'cropPlaneArtifactKey', 'crop-plane');
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'printableScalp.mat'));
    cropPlaneFile = nhpulseServiceInternal('field', config, 'cropPlaneFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'printerBedCropPlane.mat'));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    result = acsCropWarpedSkinCacheToPrinterBed(scalp.path, args{:}, ...
        'outputFile', outputFile, 'cropPlaneFile', cropPlaneFile, ...
        'cropPlaneMode', nhpulseServiceInternal('field', config, ...
        'cropPlaneMode', 'autoSelect'), ...
        'skinMaxFaces', nhpulseServiceInternal('field', config, ...
        'skinMaxFaces', 1200), ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    [planeRecord, planeHandle] = nhpulseServiceInternal('record', context, ...
        planeKey, 'nhpulse.cropPlane', result.cropPlaneFile, ...
        'label', 'Printer-bed crop plane', ...
        'parentKeys', {scalp.artifactKey}, 'parentRoles', {'sourceScalp'});
    [scalpRecord, scalpHandle] = nhpulseServiceInternal('record', context, ...
        scalpKey, 'nhpulse.scalpModel', result.cacheFile, ...
        'label', 'Printable cropped scalp', ...
        'parentKeys', {scalp.artifactKey, planeHandle.artifactKey}, ...
        'parentRoles', {'sourceScalp', 'cropPlane'});
    artifacts = struct('scalp', scalpHandle, 'cropPlane', planeHandle, ...
        'records', [planeRecord; scalpRecord]);
    output = nhpulseServiceInternal('result', 'cropScalp', context, result, ...
        artifacts, config);
end

function value = requireInput(inputs, name)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceCropScalp:MissingInput', ...
            'inputs.%s is required.', name);
    end
    value = inputs.(name);
end
