function output = nhpulseServiceSelectTarget(context, inputs, config)
% NHPULSESERVICESELECTTARGET Select/register a stimulation target voxel.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    anatomy = resolveRequired(context, inputs, 'anatomy', 'nhpulse.anatomy');
    segmentation = resolveRequired(context, inputs, 'segmentation', ...
        'nhpulse.segmentation');
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'targeting', ...
        'stimulationTarget.mat'));
    targetVoxel = nhpulseServiceInternal('field', config, 'targetVoxel', []);
    if isempty(targetVoxel)
        args = nhpulseServiceInternal('options', ...
            nhpulseServiceInternal('field', config, 'engineOptions', struct()));
        pick = acsLabelVolumeOrientation(anatomy.path, args{:}, ...
            'orientationCode', nhpulseServiceInternal('field', config, ...
            'orientationCode', 'ras'), ...
            'volumeLabel', nhpulseServiceInternal('field', config, ...
            'volumeLabel', 'Stimulation target anatomy'), ...
            'initialVoxel', nhpulseServiceInternal('field', config, ...
            'initialVoxel', []), ...
            'voxelSelectionMode', 'single', 'waitForDone', true, ...
            'doneButtonLabel', 'Accept target', ...
            'showFigures', nhpulseServiceInternal('field', config, ...
            'showFigures', true), ...
            'saveFigures', nhpulseServiceInternal('field', config, ...
            'saveFigures', true), ...
            'outputDir', fileparts(outputFile), ...
            'outputName', nhpulseServiceInternal('field', config, ...
            'qcOutputName', 'stimulationTargetPicker'), ...
            'closeFigure', nhpulseServiceInternal('field', config, ...
            'closeFigure', false), ...
            'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
        targetVoxel = double(pick.selectedVoxels(1, :));
        selectionMode = 'interactive';
    else
        targetVoxel = double(targetVoxel(:).');
        selectionMode = 'providedVoxel';
    end
    if numel(targetVoxel) ~= 3 || any(~isfinite(targetVoxel))
        error('nhpulseServiceSelectTarget:BadTargetVoxel', ...
            'targetVoxel must contain three finite voxel coordinates.');
    end
    voxelSize = nhpulseServiceInternal('field', config, 'voxelSizeMm', []);
    if isempty(voxelSize)
        targetWorld = nan(1, 3);
    else
        voxelSize = double(voxelSize(:).');
        if numel(voxelSize) ~= 3
            error('nhpulseServiceSelectTarget:BadVoxelSize', ...
                'voxelSizeMm must contain three values.');
        end
        targetWorld = targetVoxel .* voxelSize;
    end
    result = struct('createdOn', char(datetime('now')), ...
        'type', 'stimulationTargetSelection', ...
        'targetVoxel', targetVoxel, 'targetWorldMm', targetWorld, ...
        'selectionMode', selectionMode, ...
        'source', struct('anatomyFile', anatomy.path, ...
        'segmentationFile', segmentation.path));
    folder = fileparts(outputFile);
    if exist(folder, 'dir') ~= 7, mkdir(folder); end
    targetSelection = result;
    save(outputFile, 'targetSelection', '-v7.3');
    [record, handle] = nhpulseServiceInternal('record', context, ...
        nhpulseServiceInternal('field', config, 'artifactKey', ...
        'stimulation-target'), 'nhpulse.target', outputFile, ...
        'label', 'Stimulation target', ...
        'parentKeys', {anatomy.artifactKey, segmentation.artifactKey}, ...
        'parentRoles', {'sourceAnatomy', 'tissueSegmentation'});
    output = nhpulseServiceInternal('result', 'selectTarget', context, ...
        result, struct('target', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceSelectTarget:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end
