function output = nhpulseServiceGenerateLeadField(context, inputs, config)
% NHPULSESERVICEGENERATELEADFIELD Solve/register a candidate lead field.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.candidateLayout');
    segmentation = resolveRequired(context, inputs, 'segmentation', ...
        'nhpulse.segmentation');
    layoutValue = nhpulseServiceInternal('loadValue', layout);
    mode = lower(char(nhpulseServiceInternal('field', config, 'mode', 'roast')));
    simulationTag = nhpulseServiceInternal('field', config, 'simulationTag', ...
        sprintf('%s_lf%02d', context.runId, numel(layoutValue.names)));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    switch mode
        case 'roast'
            result = acsGenerateRoastLeadField(layoutValue, args{:}, ...
                'simulationTag', simulationTag, ...
                'segMaskFile', segmentation.path, ...
                'execute', nhpulseServiceInternal('field', config, 'execute', true), ...
                'saveReport', true);
        case 'dummy'
            result = acsGenerateDummyRoastLeadField(layoutValue, args{:}, ...
                'simulationTag', simulationTag, ...
                'force', nhpulseServiceInternal('field', config, 'force', false), ...
                'saveReport', true, ...
                'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
        otherwise
            error('nhpulseServiceGenerateLeadField:BadMode', ...
                'config.mode must be roast or dummy.');
    end
    % The request report is the stable reloadable service artifact. It stores
    % the simulation tag and paths needed by optimization; the large ROAST
    % result remains a referenced engine product.
    artifactFile = primaryFile(result, ...
        {'reportMat', 'leadFieldResultMat', 'requestedLeadFieldResultMat'});
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'lead-field');
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.leadField', artifactFile, 'label', 'Candidate lead field', ...
        'parentKeys', {segmentation.artifactKey, layout.artifactKey}, ...
        'parentRoles', {'electricalSegmentation', 'candidateLayout'}, ...
        'metadata', struct('mode', mode, 'simulationTag', simulationTag));
    output = nhpulseServiceInternal('result', 'generateLeadField', context, ...
        result, struct('leadField', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceGenerateLeadField:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end

function fileName = primaryFile(value, fields)
    for i = 1:numel(fields)
        if isfield(value, fields{i}) && ~isempty(value.(fields{i})) && ...
                exist(char(value.(fields{i})), 'file') == 2
            fileName = char(value.(fields{i}));
            return;
        end
    end
    error('nhpulseServiceGenerateLeadField:OutputMissing', ...
        'Lead-field engine did not produce a saved result or request report.');
end
