function output = nhpulseServicePlanRetention(context, inputs, config)
% NHPULSESERVICEPLANRETENTION Plan/register Velcro retention anchors.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.combinedLayout');
    scalp = resolveRequired(context, inputs, 'scalp', 'nhpulse.scalpModel');
    exclusion = resolveOptional(context, inputs, 'anatomicalExclusion', ...
        'nhpulse.exclusion');
    implants = resolveMany(context, inputs, 'implantExclusions', ...
        'nhpulse.exclusion');
    layoutValue = nhpulseServiceInternal('loadValue', layout);
    outputDir = nhpulseServiceInternal('field', config, 'outputDir', ...
        fileparts(nhpulseServiceInternal('outputPath', context, ...
        'manufacturing', 'placeholder')));
    manufacturingTag = nhpulseServiceInternal('field', config, ...
        'manufacturingTag', [context.runId '_cap']);
    common = manufacturingArgs(config, scalp, exclusion, implants, ...
        outputDir, manufacturingTag);
    preflight = acsBuildCapMakerManufacturingStl(layoutValue, common{:}, ...
        'strapMode', 'none', 'preflightOnly', true, ...
        'force', nhpulseServiceInternal('field', config, 'force', false));
    planFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        fullfile(outputDir, [manufacturingTag '_velcroAnchors.mat']));
    planOptions = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'plannerOptions', struct()));
    earFile = '';
    if ~isempty(exclusion), earFile = exclusion.path; end
    result = acsPlanVelcroAnchors(preflight, planOptions{:}, ...
        'earExclusionFile', earFile, 'outputFile', planFile, ...
        'editMode', nhpulseServiceInternal('field', config, 'editMode', 'auto'), ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    parentKeys = {layout.artifactKey, scalp.artifactKey};
    parentRoles = {'capLayout', 'placementSurface'};
    if ~isempty(exclusion)
        parentKeys{end + 1} = exclusion.artifactKey;
        parentRoles{end + 1} = 'anatomicalExclusions';
    end
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'retention-plan');
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.retentionPlan', result.outputFile, ...
        'label', 'Velcro attachment anchor plan', ...
        'parentKeys', parentKeys, 'parentRoles', parentRoles);
    combinedResult = struct('preflight', preflight, 'plan', result);
    output = nhpulseServiceInternal('result', 'planRetention', context, ...
        combinedResult, struct('retentionPlan', handle, 'records', record), config);
end

function args = manufacturingArgs(config, scalp, exclusion, implants, outputDir, tag)
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'manufacturingOptions', struct()));
    implantFiles = {implants.path};
    earFile = '';
    if ~isempty(exclusion), earFile = exclusion.path; end
    args = [args, {'skinCacheFile', scalp.path, 'outputDir', outputDir, ...
        'manufacturingTag', tag, 'earExclusionMode', 'never', ...
        'earExclusionFile', earFile, 'implantExclusionFile', implantFiles, ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true)}];
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServicePlanRetention:MissingInput', 'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end

function handle = resolveOptional(context, inputs, name, type)
    handle = [];
    if isstruct(inputs) && isfield(inputs, name) && ~isempty(inputs.(name))
        handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
            'expectedType', type);
    end
end

function handles = resolveMany(context, inputs, name, type)
    handles = repmat(struct(), 0, 1);
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name)), return; end
    refs = inputs.(name); if ~iscell(refs), refs = num2cell(refs); end
    for i = 1:numel(refs)
        handles(i, 1) = nhpulseServiceInternal('resolve', context, refs{i}, ...
            'expectedType', type);
    end
end
