function output = nhpulseServiceDefineExclusions(context, inputs, config)
% NHPULSESERVICEDEFINEEXCLUSIONS Define/register ear and painted exclusions.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    scalp = nhpulseServiceInternal('resolve', context, ...
        requireInput(inputs, 'scalp'), 'expectedType', 'nhpulse.scalpModel');
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'anatomical-exclusions');
    outputFile = nhpulseServiceInternal('field', config, 'outputFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'anatomicalExclusions.mat'));
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    result = acsSelectEarExclusionSpheres(scalp.path, args{:}, ...
        'outputFile', outputFile, ...
        'editMode', nhpulseServiceInternal('field', config, 'editMode', 'auto'), ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.exclusion', result.outputFile, ...
        'label', 'Ear and painted manufacturing exclusions', ...
        'parentKeys', {scalp.artifactKey}, 'parentRoles', {'placementSurface'});
    output = nhpulseServiceInternal('result', 'defineExclusions', context, ...
        result, struct('exclusions', handle, 'records', record), config);
end

function value = requireInput(inputs, name)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceDefineExclusions:MissingInput', ...
            'inputs.%s is required.', name);
    end
    value = inputs.(name);
end
