function output = nhpulseServiceBuildManufacturing(context, inputs, config)
% NHPULSESERVICEBUILDMANUFACTURING Build/register final cap geometry and STLs.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.combinedLayout');
    scalp = resolveRequired(context, inputs, 'scalp', 'nhpulse.scalpModel');
    exclusion = resolveOptional(context, inputs, 'anatomicalExclusion', ...
        'nhpulse.exclusion');
    retention = resolveOptional(context, inputs, 'retentionPlan', ...
        'nhpulse.retentionPlan');
    implants = resolveMany(context, inputs, 'implantExclusions', ...
        'nhpulse.exclusion');
    layoutValue = nhpulseServiceInternal('loadValue', layout);
    outputDir = nhpulseServiceInternal('field', config, 'outputDir', ...
        fileparts(nhpulseServiceInternal('outputPath', context, ...
        'manufacturing', 'placeholder')));
    tag = nhpulseServiceInternal('field', config, ...
        'manufacturingTag', [context.runId '_cap']);
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    earFile = '';
    if ~isempty(exclusion), earFile = exclusion.path; end
    implantFiles = {implants.path};
    velcroMode = 'none'; velcroFile = '';
    if ~isempty(retention)
        velcroMode = 'file'; velcroFile = retention.path;
    end
    result = acsBuildCapMakerManufacturingStl(layoutValue, args{:}, ...
        'skinCacheFile', scalp.path, 'outputDir', outputDir, ...
        'manufacturingTag', tag, 'earExclusionMode', 'never', ...
        'earExclusionFile', earFile, 'implantExclusionFile', implantFiles, ...
        'strapMode', nhpulseServiceInternal('field', config, 'strapMode', 'none'), ...
        'velcroAnchorMode', velcroMode, 'velcroAnchorFile', velcroFile, ...
        'preflightOnly', false, 'saveMeshMat', true, ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    parentKeys = {layout.artifactKey, scalp.artifactKey};
    parentRoles = {'capLayout', 'manufacturingSurface'};
    if ~isempty(exclusion)
        parentKeys{end + 1} = exclusion.artifactKey;
        parentRoles{end + 1} = 'anatomicalExclusions';
    end
    for i = 1:numel(implants)
        parentKeys{end + 1} = implants(i).artifactKey; %#ok<AGROW>
        parentRoles{end + 1} = 'implantKeepout'; %#ok<AGROW>
    end
    if ~isempty(retention)
        parentKeys{end + 1} = retention.artifactKey;
        parentRoles{end + 1} = 'retentionPlan';
    end
    designKey = nhpulseServiceInternal('field', config, ...
        'designArtifactKey', 'manufacturing-design');
    reportFile = primaryFile(result, {'reportMat', 'outputFile'});
    [designRecord, designHandle] = nhpulseServiceInternal('record', context, ...
        designKey, 'nhpulse.manufacturingGeometry', reportFile, ...
        'label', 'Final dual-material cap design', ...
        'parentKeys', parentKeys, 'parentRoles', parentRoles);
    [tpeRecord, tpeHandle] = nhpulseServiceInternal('record', context, ...
        nhpulseServiceInternal('field', config, 'tpeArtifactKey', 'tpe-stl'), ...
        'nhpulse.manufacturingStl', result.tpeStlFile, ...
        'label', 'Final TPE cap STL', 'parentKeys', {designHandle.artifactKey}, ...
        'parentRoles', {'manufacturingDesign'}, ...
        'metadata', struct('material', 'TPE'));
    [plaRecord, plaHandle] = nhpulseServiceInternal('record', context, ...
        nhpulseServiceInternal('field', config, 'plaArtifactKey', 'pla-stl'), ...
        'nhpulse.manufacturingStl', result.plaStlFile, ...
        'label', 'Final PLA support STL', 'parentKeys', {designHandle.artifactKey}, ...
        'parentRoles', {'manufacturingDesign'}, ...
        'metadata', struct('material', 'PLA'));
    artifacts = struct('design', designHandle, 'tpeStl', tpeHandle, ...
        'plaStl', plaHandle, 'records', [designRecord; tpeRecord; plaRecord]);
    output = nhpulseServiceInternal('result', 'buildManufacturing', context, ...
        result, artifacts, config);
end

function fileName = primaryFile(value, fields)
    for i = 1:numel(fields)
        if isfield(value, fields{i}) && ~isempty(value.(fields{i})) && ...
                exist(char(value.(fields{i})), 'file') == 2
            fileName = char(value.(fields{i})); return;
        end
    end
    error('nhpulseServiceBuildManufacturing:ReportMissing', ...
        'Manufacturing engine did not save a report MAT file.');
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceBuildManufacturing:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end

function handle = resolveOptional(context, inputs, name, type)
    handle = [];
    if isstruct(inputs) && isfield(inputs, name) && ~isempty(inputs.(name))
        handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
            'expectedType', type);
    end
end

function handles = resolveMany(context, inputs, name, type)
    handles = repmat(struct(), 0, 1);
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name)), return; end
    refs = inputs.(name); if ~iscell(refs), refs = num2cell(refs); end
    for i = 1:numel(refs)
        handles(i, 1) = nhpulseServiceInternal('resolve', context, refs{i}, ...
            'expectedType', type);
    end
end
