function output = nhpulseServiceOptimizeMontage(context, inputs, config)
% NHPULSESERVICEOPTIMIZEMONTAGE Optimize/register a sparse tES montage.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    leadField = resolveRequired(context, inputs, 'leadField', 'nhpulse.leadField');
    target = resolveRequired(context, inputs, 'target', 'nhpulse.target');
    layout = resolveRequired(context, inputs, 'layout', 'nhpulse.candidateLayout');
    lf = nhpulseServiceInternal('loadValue', leadField);
    targetValue = nhpulseServiceInternal('loadValue', target);
    voxel = nhpulseServiceInternal('targetVoxel', targetValue);
    orientation = nhpulseServiceInternal('field', config, ...
        'orientation', [0 0 1]);
    mode = nhpulseServiceInternal('field', config, 'searchMode', 'globalCvx');
    args = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'engineOptions', struct()));
    result = acsOptimizeSparseRoastLeadField(lf.t1File, lf.simulationTag, ...
        voxel, args{:}, 'orientation', orientation, ...
        'targetRadiusMm', nhpulseServiceInternal('field', config, ...
        'targetRadiusMm', 2), ...
        'activeElectrodeCount', nhpulseServiceInternal('field', config, ...
        'activeElectrodeCount', 8), ...
        'totalCurrentMa', nhpulseServiceInternal('field', config, ...
        'totalCurrentMa', 2), ...
        'searchMode', mode, ...
        'targetingTag', nhpulseServiceInternal('field', config, ...
        'targetingTag', [context.runId '_optimized']), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'saveReport', true, ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    key = nhpulseServiceInternal('field', config, ...
        'artifactKey', 'optimized-montage');
    metadata = struct('selectedNames', {cellstr(result.selectedNames(:))}, ...
        'selectedCurrentsMa', double(result.selectedCurrentsMa(:)));
    [record, handle] = nhpulseServiceInternal('record', context, key, ...
        'nhpulse.optimizedMontage', result.reportMat, ...
        'label', 'Optimized sparse tES montage', ...
        'parentKeys', {leadField.artifactKey, target.artifactKey, ...
        layout.artifactKey}, ...
        'parentRoles', {'leadField', 'stimulationTarget', 'candidateLayout'}, ...
        'metadata', metadata);
    output = nhpulseServiceInternal('result', 'optimizeMontage', context, ...
        result, struct('montage', handle, 'records', record), config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServiceOptimizeMontage:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end
