function output = nhpulseServicePlaceHeadpost(context, inputs, config)
% NHPULSESERVICEPLACEHEADPOST Place/register headpost and cap keepout.

    if nargin < 3, config = struct(); end
    nhpulseServiceInternal('validateContext', context);
    source = resolveRequired(context, inputs, 'source', ...
        {'nhpulse.implantTrace', 'nhpulse.exclusion'});
    scalp = resolveRequired(context, inputs, 'scalp', 'nhpulse.scalpModel');
    segmentation = resolveRequired(context, inputs, 'segmentation', ...
        'nhpulse.segmentation');
    sourceValue = nhpulseServiceInternal('loadValue', source);
    placementFile = nhpulseServiceInternal('field', config, 'placementFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'headpostPlacement.mat'));
    placementArgs = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'placementOptions', struct()));
    placement = acsPlanHeadpostPlacement(sourceValue, scalp.path, ...
        placementArgs{:}, 'maskFile', segmentation.path, ...
        'outputFile', placementFile, ...
        'interactive', nhpulseServiceInternal('field', config, 'interactive', true), ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    [placementRecord, placementHandle] = nhpulseServiceInternal('record', ...
        context, nhpulseServiceInternal('field', config, ...
        'placementArtifactKey', 'implant-placement'), ...
        'nhpulse.implantPlacement', placement.outputFile, ...
        'label', 'Headpost placement', ...
        'parentKeys', {source.artifactKey, scalp.artifactKey, ...
        segmentation.artifactKey}, ...
        'parentRoles', {'observedTrace', 'placementSurface', ...
        'tissueSegmentation'});
    keepoutFile = nhpulseServiceInternal('field', config, 'keepoutFile', ...
        nhpulseServiceInternal('outputPath', context, 'geometry', ...
        'headpostKeepout.mat'));
    keepoutArgs = nhpulseServiceInternal('options', ...
        nhpulseServiceInternal('field', config, 'keepoutOptions', struct()));
    keepout = acsMakeHeadpostExclusionFromPlacement(placement, scalp.path, ...
        keepoutArgs{:}, 'outputFile', keepoutFile, ...
        'marginMm', nhpulseServiceInternal('field', config, 'marginMm', 5), ...
        'force', nhpulseServiceInternal('field', config, 'force', false), ...
        'showFigures', nhpulseServiceInternal('field', config, 'showFigures', true), ...
        'saveFigures', nhpulseServiceInternal('field', config, 'saveFigures', true), ...
        'verbose', nhpulseServiceInternal('field', config, 'verbose', true));
    [keepoutRecord, keepoutHandle] = nhpulseServiceInternal('record', ...
        context, nhpulseServiceInternal('field', config, ...
        'keepoutArtifactKey', 'implant-keepout'), ...
        'nhpulse.exclusion', keepout.outputFile, ...
        'label', 'Headpost manufacturing keepout', ...
        'parentKeys', {placementHandle.artifactKey, scalp.artifactKey}, ...
        'parentRoles', {'implantPlacement', 'placementSurface'});
    result = struct('placement', placement, 'keepout', keepout);
    artifacts = struct('placement', placementHandle, 'keepout', keepoutHandle, ...
        'records', [placementRecord; keepoutRecord]);
    output = nhpulseServiceInternal('result', 'placeHeadpost', context, ...
        result, artifacts, config);
end

function handle = resolveRequired(context, inputs, name, type)
    if ~isstruct(inputs) || ~isfield(inputs, name) || isempty(inputs.(name))
        error('nhpulseServicePlaceHeadpost:MissingInput', ...
            'inputs.%s is required.', name);
    end
    handle = nhpulseServiceInternal('resolve', context, inputs.(name), ...
        'expectedType', type);
end
