function result = nhpulseTestOrthogonalTesEegOptimization()
% NHPULSETESTORTHOGONALTESEEGOPTIMIZATION Fast linear-control regression test.

    transfer = struct();
    transfer.tesNames = {'T1'; 'T2'; 'T3'};
    transfer.eegNames = {'E1'; 'E2'; 'E3'};
    transfer.transferMatrixVPerMa = 1e-6 * [ ...
         1,  0, -1; ...
         0,  1, -1; ...
        -1, -1,  2];
    transfer.reportMat = fullfile(tempdir, 'nhpulse_test_tes_eeg_transfer.mat');
    layout = struct('tesNames', {transfer.tesNames}, ...
        'names', {[transfer.tesNames; transfer.eegNames]}, ...
        't1File', fullfile(tempdir, 'nhpulse_test_anatomy.nii'));
    reportFile = fullfile(tempdir, 'nhpulse_test_orthogonal_tes_eeg.mat');
    out = acsOptimizeOrthogonalTesEegTopography(layout, ...
        {'T1', 1, 'T3', -1}, ...
        'transferMatrix', transfer, ...
        'nStarts', 6, ...
        'maxIterations', 8, ...
        'showFigures', false, ...
        'saveFigures', false, ...
        'verbose', false, ...
        'outputFile', reportFile);

    assert(abs(sum(out.alternateCurrentsMa)) < 1e-8, ...
        'Alternate recipe is not current-balanced.');
    assert(norm(out.alternateCurrentsMa, 1) <= 2*out.totalCurrentMa + 1e-8, ...
        'Alternate recipe exceeds the total-current limit.');
    assert(max(abs(out.alternateCurrentsMa)) <= ...
        out.maxCurrentPerElectrodeMa + 1e-8, ...
        'Alternate recipe exceeds the per-contact current limit.');
    assert(abs(out.weightedTopographyCorrelation) < 1e-6, ...
        'Alternate EEG prediction is not orthogonal to baseline.');
    result = struct('passed', true, ...
        'weightedTopographyCorrelation', out.weightedTopographyCorrelation, ...
        'alternateCurrentsMa', out.alternateCurrentsMa);
end
